{ pkgs, ... }:
{
  projectRootFile = "flake.nix";

  # Nix
  programs.nixpkgs-fmt.enable = true;

  # JS
  programs.biome.enable = true;
  settings.formatter.biome = {
    excludes = [
      # Autogenerated
      "docs/docs/b6-api-documentation.md"
      "frontend/src/types/generated/*"
      "frontend/src/assets/**/*"
    ];
  };

  # Go
  programs.gofmt.enable = true;
  settings.formatter.gofmt.excludes = [
    "*.pb.go"
    # This file is autogenerated, so we won't worry about formatting it.
    "src/diagonal.works/b6/api/functions/docs.go"
  ];

  # Python
  programs.ruff.enable = true;

  settings.excludes = [
    "src/diagonal.works/b6/cmd/b6/js/*"
  ];
}
