// Code generated by goyacc shell.y. DO NOT EDIT.

//line shell.y:2

package api

import __yyfmt__ "fmt"

//line shell.y:4

import (
	pb "diagonal.works/b6/proto"
)

//line shell.y:21
type yySymType struct {
	yys   int
	node  *pb.NodeProto
	nodes []*pb.NodeProto
}

const FLOAT = 57346
const INT = 57347
const FEATURE_ID = 57348
const SYMBOL = 57349
const STRING = 57350
const TAG_KEY = 57351
const ARROW = 57352

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"','",
	"'('",
	"')'",
	"'|'",
	"'{'",
	"'}'",
	"'['",
	"']'",
	"'='",
	"'&'",
	"FLOAT",
	"INT",
	"FEATURE_ID",
	"SYMBOL",
	"STRING",
	"TAG_KEY",
	"ARROW",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 90

var yyAct = [...]int{
	10, 37, 2, 17, 5, 44, 16, 31, 18, 24,
	20, 55, 12, 13, 14, 23, 11, 15, 22, 33,
	30, 43, 29, 18, 17, 28, 24, 16, 42, 18,
	35, 45, 34, 12, 13, 14, 4, 11, 15, 51,
	40, 3, 38, 39, 41, 50, 54, 49, 53, 33,
	33, 33, 33, 48, 61, 62, 57, 58, 59, 60,
	17, 36, 52, 16, 20, 18, 26, 47, 19, 12,
	13, 14, 23, 11, 15, 19, 19, 63, 56, 46,
	19, 25, 1, 27, 21, 32, 9, 8, 7, 6,
}

var yyPact = [...]int{
	19, -1000, 61, -1000, -2, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 77, -1000, -1000, 54, 5, 19, 13, 19,
	25, 55, -1000, 52, -1000, 30, 25, 1, 19, -1000,
	73, 56, 40, 32, 50, 36, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 19, -6, 69, -1000, -1000, 13, 13,
	13, 13, 25, 25, 68, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 4, 89, 88, 41, 18, 2, 87, 86, 1,
	0, 7, 85, 84, 83, 82,
}

var yyR1 = [...]int{
	0, 15, 6, 6, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 2, 3, 3, 4, 4, 4, 13,
	13, 5, 5, 7, 7, 14, 14, 8, 10, 11,
	11, 11, 11, 11, 11, 12, 12, 12, 12, 9,
	9,
}

var yyR2 = [...]int{
	0, 1, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 3, 3, 1, 2, 1, 2,
	1, 1, 1, 5, 4, 1, 3, 3, 3, 1,
	3, 3, 3, 3, 1, 1, 3, 1, 3, 1,
	1,
}

var yyChk = [...]int{
	-1000, -15, -6, -4, 17, -1, -2, -3, -7, -8,
	-10, 18, 14, 15, 16, 19, 8, 5, 10, 7,
	12, -13, -5, 17, -1, 4, 12, -14, 20, 17,
	-6, -11, -12, -10, 19, 17, -4, -9, 17, 18,
	-5, 14, -9, 20, 4, -6, 6, 11, 13, 7,
	13, 7, 12, 12, -6, 17, 9, -11, -11, -11,
	-11, -9, -9, 9,
}

var yyDef = [...]int{
	0, -2, 1, 3, 16, 18, 4, 5, 6, 7,
	8, 9, 10, 11, 12, 0, 0, 0, 0, 0,
	0, 17, 20, 21, 22, 0, 0, 0, 0, 25,
	0, 0, 29, 34, 35, 37, 2, 15, 39, 40,
	19, 13, 14, 0, 0, 0, 27, 28, 0, 0,
	0, 0, 0, 0, 0, 26, 24, 30, 32, 31,
	33, 36, 38, 23,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 13, 3,
	5, 6, 3, 3, 4, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 12, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 10, 3, 11, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 8, 7, 9,
}

var yyTok2 = [...]int{
	2, 3, 14, 15, 16, 17, 18, 19, 20,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line shell.y:33
		{
			yylex.(*lexer).Top = reduceRootCall(yyDollar[1].node, yylex.(*lexer))
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:39
		{
			yyVAL.node = reducePipeline(yyDollar[1].node, yyDollar[3].node, yylex.(*lexer))
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:57
		{
			yyVAL.node = reduceLatLng(yyDollar[1].node, yyDollar[3].node, yylex.(*lexer))
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:63
		{
			yyVAL.node = reduceTag(yyDollar[1].node, yyDollar[3].node, yylex.(*lexer))
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:67
		{
			yyVAL.node = reduceTag(yyDollar[1].node, yyDollar[3].node, yylex.(*lexer))
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line shell.y:73
		{
			yyVAL.node = reduceCall(yyDollar[1].node, yylex.(*lexer))
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line shell.y:77
		{
			yyVAL.node = reduceCallWithArgs(yyDollar[1].node, yyDollar[2].nodes, yylex.(*lexer))
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line shell.y:84
		{
			yyVAL.nodes = reduceArgs(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line shell.y:88
		{
			yyVAL.nodes = reduceArg(yyDollar[1].node)
		}
	case 23:
		yyDollar = yyS[yypt-5 : yypt+1]
//line shell.y:98
		{
			yyVAL.node = reduceLambda(yyDollar[2].nodes, yyDollar[4].node)
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line shell.y:102
		{
			yyVAL.node = reduceLambdaWithoutArgs(yyDollar[3].node)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line shell.y:108
		{
			yyVAL.nodes = reduceSymbolsSymbol(yyDollar[1].node)
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:112
		{
			yyVAL.nodes = reduceSymbolsSymbols(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:118
		{
			yyVAL.node = yyDollar[2].node
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:124
		{
			yyVAL.node = yyDollar[2].node
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:131
		{
			yyVAL.node = reduceAnd(yyDollar[1].node, yyDollar[3].node)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:135
		{
			yyVAL.node = reduceAnd(yyDollar[1].node, yyDollar[3].node)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:139
		{
			yyVAL.node = reduceOr(yyDollar[1].node, yyDollar[3].node)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:143
		{
			yyVAL.node = reduceOr(yyDollar[1].node, yyDollar[3].node)
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line shell.y:150
		{
			yyVAL.node = reduceTagKey(yyDollar[1].node)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:154
		{
			yyVAL.node = reduceTagKeyValue(yyDollar[1].node, yyDollar[3].node)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line shell.y:158
		{
			yyVAL.node = reduceTagKey(yyDollar[1].node)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line shell.y:162
		{
			yyVAL.node = reduceTagKeyValue(yyDollar[1].node, yyDollar[3].node)
		}
	}
	goto yystack /* stack new state and value */
}
