schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.110.0"
    hash = "sha256-56s9lxMqlQ2sFZOteDv9n0zCC0MTwoczCqSQY2+bT+c="
  [mod."cloud.google.com/go/compute"]
    version = "v1.19.0"
    hash = "sha256-zYLTa8JyaZ5UdPwl1YqXSkhTThRBjp7bDDtjmdmPmfA="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.2.3"
    hash = "sha256-kYB1FTQRdTDqCqJzSU/jJYbVUGyxbkASUKbEs36FUyU="
  [mod."cloud.google.com/go/iam"]
    version = "v0.13.0"
    hash = "sha256-ZdpvP9zPcuG7MPZ9fbAEnjI4zIDRbNSPmOaHyTEZ914="
  [mod."cloud.google.com/go/storage"]
    version = "v1.30.1"
    hash = "sha256-4lC0XaLSQDnVBmNLIauiWnGXq+Ax57r8fcMxXFMCCNE="
  [mod."github.com/apache/beam"]
    version = "v2.32.0+incompatible"
    hash = "sha256-Tt8lX2e8G2TLT+Qqcq0YJidvAjLQQsBKajiDajyxw2A="
  [mod."github.com/golang/geo"]
    version = "v0.0.0-20190916061304-5b978397cfec"
    hash = "sha256-I3JT0rEvkpxWDtbruK57XZaby1CHFQL4SlqzRAh1CdA="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.0"
    hash = "sha256-C7b9hMnSFieaLmo3sycZriDglLo++nwAgTqnp2qkN54="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.2.3"
    hash = "sha256-4yaBdpdRuv5vkGlwxKPlZ/IVSeHlcP9PJaLcyn4wNJk="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.8.0"
    hash = "sha256-uxJgSGs78x98m7k+xI2ux/l7A7f8Lp6gn3ufRHqx7DM="
  [mod."github.com/lukeroth/gdal"]
    version = "v0.0.0-20230818145556-62d5095a1cda"
    hash = "sha256-BCphXhtQnXEPaIVDCj0g9Gmc5M4hLOTscuuEz6aHSMs="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."golang.org/x/crypto"]
    version = "v0.1.0"
    hash = "sha256-0oZWBSiW5Pd/2a1p2beuoelDe0CpfXZhrg/qPduJlYs="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230310171629-522b1b587ee0"
    hash = "sha256-C/uVh07/uaKihQ4OtkT0tOUgjnKWabBEPANyA6wgPHo="
  [mod."golang.org/x/mod"]
    version = "v0.10.0"
    hash = "sha256-g0T2wz+K0nhPWdVQJRGGqEqzlTHMBahv+9C3y090eIM="
  [mod."golang.org/x/net"]
    version = "v0.9.0"
    hash = "sha256-EG5GRDq282twyce8uugsDTjMz1pNn6zPcyVTZmSiJ14="
  [mod."golang.org/x/oauth2"]
    version = "v0.7.0"
    hash = "sha256-KQU6ZlzWMvBjBdCAdyZbdwXkyqIskKFWmJIM11m1shY="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.7.0"
    hash = "sha256-GotRHJaas/q3L+tFam0q3oQ1rc8GDStt7wnz9h8MTEU="
  [mod."golang.org/x/text"]
    version = "v0.10.0"
    hash = "sha256-pt4Ce9+Bvf7f0Vo8oUZ71F1aSCcCxsx6Lg0cvanq7x8="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20220907171357-04be3eba64a2"
    hash = "sha256-6+zueutgefIYmgXinOflz8qGDDDj0Zhv+2OkGhBTKno="
  [mod."google.golang.org/api"]
    version = "v0.118.0"
    hash = "sha256-4Hv8/ymOh6NRbTOXwqCSKEeASeHADh9haybzo38qzBE="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230403163135-c38d8f061ccd"
    hash = "sha256-PcS7QF2xs0wzMz/F14UyKL75wlvnYITdLYpCRASJhqg="
  [mod."google.golang.org/grpc"]
    version = "v1.54.0"
    hash = "sha256-2HzpK4s9zAGUv/26wChxbfkX3t4WB1bLM96O5gkQmro="
  [mod."google.golang.org/protobuf"]
    version = "v1.30.0"
    hash = "sha256-Y07NKhSuJQ2w7F7MAINQyBf+/hdMHOrxwA3B4ljQQKs="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
