import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	apiSidebar: [{ type: "autogenerated", dirName: "api" }],
	docsSidebar: [{ type: "autogenerated", dirName: "documentation" }],
};

export default sidebars;
