// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   []*LiteralNodeProto `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values []*LiteralNodeProto `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *CollectionProto) Reset() {
	*x = CollectionProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionProto) ProtoMessage() {}

func (x *CollectionProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionProto.ProtoReflect.Descriptor instead.
func (*CollectionProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionProto) GetKeys() []*LiteralNodeProto {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CollectionProto) GetValues() []*LiteralNodeProto {
	if x != nil {
		return x.Values
	}
	return nil
}

type PairProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  *LiteralNodeProto `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Second *LiteralNodeProto `protobuf:"bytes,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *PairProto) Reset() {
	*x = PairProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairProto) ProtoMessage() {}

func (x *PairProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairProto.ProtoReflect.Descriptor instead.
func (*PairProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *PairProto) GetFirst() *LiteralNodeProto {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *PairProto) GetSecond() *LiteralNodeProto {
	if x != nil {
		return x.Second
	}
	return nil
}

type ModifiedFeaturesProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []*FeatureIDProto `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ModifiedFeaturesProto) Reset() {
	*x = ModifiedFeaturesProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifiedFeaturesProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifiedFeaturesProto) ProtoMessage() {}

func (x *ModifiedFeaturesProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifiedFeaturesProto.ProtoReflect.Descriptor instead.
func (*ModifiedFeaturesProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ModifiedFeaturesProto) GetIds() []*FeatureIDProto {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AppliedChangeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original []*FeatureIDProto `protobuf:"bytes,1,rep,name=original,proto3" json:"original,omitempty"`
	Modified []*FeatureIDProto `protobuf:"bytes,2,rep,name=modified,proto3" json:"modified,omitempty"`
}

func (x *AppliedChangeProto) Reset() {
	*x = AppliedChangeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppliedChangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedChangeProto) ProtoMessage() {}

func (x *AppliedChangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedChangeProto.ProtoReflect.Descriptor instead.
func (*AppliedChangeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AppliedChangeProto) GetOriginal() []*FeatureIDProto {
	if x != nil {
		return x.Original
	}
	return nil
}

func (x *AppliedChangeProto) GetModified() []*FeatureIDProto {
	if x != nil {
		return x.Modified
	}
	return nil
}

type NodeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Node:
	//	*NodeProto_Symbol
	//	*NodeProto_Literal
	//	*NodeProto_Call
	//	*NodeProto_Lambda_
	Node  isNodeProto_Node `protobuf_oneof:"node"`
	Begin int32            `protobuf:"varint,6,opt,name=Begin,proto3" json:"Begin,omitempty"`
	End   int32            `protobuf:"varint,7,opt,name=End,proto3" json:"End,omitempty"`
}

func (x *NodeProto) Reset() {
	*x = NodeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeProto) ProtoMessage() {}

func (x *NodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeProto.ProtoReflect.Descriptor instead.
func (*NodeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (m *NodeProto) GetNode() isNodeProto_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (x *NodeProto) GetSymbol() string {
	if x, ok := x.GetNode().(*NodeProto_Symbol); ok {
		return x.Symbol
	}
	return ""
}

func (x *NodeProto) GetLiteral() *LiteralNodeProto {
	if x, ok := x.GetNode().(*NodeProto_Literal); ok {
		return x.Literal
	}
	return nil
}

func (x *NodeProto) GetCall() *CallNodeProto {
	if x, ok := x.GetNode().(*NodeProto_Call); ok {
		return x.Call
	}
	return nil
}

func (x *NodeProto) GetLambda_() *LambdaNodeProto {
	if x, ok := x.GetNode().(*NodeProto_Lambda_); ok {
		return x.Lambda_
	}
	return nil
}

func (x *NodeProto) GetBegin() int32 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *NodeProto) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type isNodeProto_Node interface {
	isNodeProto_Node()
}

type NodeProto_Symbol struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3,oneof"`
}

type NodeProto_Literal struct {
	Literal *LiteralNodeProto `protobuf:"bytes,2,opt,name=literal,proto3,oneof"`
}

type NodeProto_Call struct {
	Call *CallNodeProto `protobuf:"bytes,3,opt,name=call,proto3,oneof"`
}

type NodeProto_Lambda_ struct {
	Lambda_ *LambdaNodeProto `protobuf:"bytes,4,opt,name=lambda_,json=lambda,proto3,oneof"`
}

func (*NodeProto_Symbol) isNodeProto_Node() {}

func (*NodeProto_Literal) isNodeProto_Node() {}

func (*NodeProto_Call) isNodeProto_Node() {}

func (*NodeProto_Lambda_) isNodeProto_Node() {}

type LiteralNodeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*LiteralNodeProto_NilValue
	//	*LiteralNodeProto_BoolValue
	//	*LiteralNodeProto_StringValue
	//	*LiteralNodeProto_IntValue
	//	*LiteralNodeProto_FloatValue
	//	*LiteralNodeProto_CollectionValue
	//	*LiteralNodeProto_PairValue
	//	*LiteralNodeProto_FeatureValue
	//	*LiteralNodeProto_QueryValue
	//	*LiteralNodeProto_FeatureIDValue
	//	*LiteralNodeProto_PointValue
	//	*LiteralNodeProto_PathValue
	//	*LiteralNodeProto_AreaValue
	//	*LiteralNodeProto_AppliedChangeValue
	//	*LiteralNodeProto_GeoJSONValue
	//	*LiteralNodeProto_TagValue
	Value isLiteralNodeProto_Value `protobuf_oneof:"value"`
}

func (x *LiteralNodeProto) Reset() {
	*x = LiteralNodeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiteralNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiteralNodeProto) ProtoMessage() {}

func (x *LiteralNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiteralNodeProto.ProtoReflect.Descriptor instead.
func (*LiteralNodeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (m *LiteralNodeProto) GetValue() isLiteralNodeProto_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *LiteralNodeProto) GetNilValue() bool {
	if x, ok := x.GetValue().(*LiteralNodeProto_NilValue); ok {
		return x.NilValue
	}
	return false
}

func (x *LiteralNodeProto) GetBoolValue() bool {
	if x, ok := x.GetValue().(*LiteralNodeProto_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *LiteralNodeProto) GetStringValue() string {
	if x, ok := x.GetValue().(*LiteralNodeProto_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *LiteralNodeProto) GetIntValue() int64 {
	if x, ok := x.GetValue().(*LiteralNodeProto_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *LiteralNodeProto) GetFloatValue() float64 {
	if x, ok := x.GetValue().(*LiteralNodeProto_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *LiteralNodeProto) GetCollectionValue() *CollectionProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_CollectionValue); ok {
		return x.CollectionValue
	}
	return nil
}

func (x *LiteralNodeProto) GetPairValue() *PairProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_PairValue); ok {
		return x.PairValue
	}
	return nil
}

func (x *LiteralNodeProto) GetFeatureValue() *FeatureProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_FeatureValue); ok {
		return x.FeatureValue
	}
	return nil
}

func (x *LiteralNodeProto) GetQueryValue() *QueryProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_QueryValue); ok {
		return x.QueryValue
	}
	return nil
}

func (x *LiteralNodeProto) GetFeatureIDValue() *FeatureIDProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_FeatureIDValue); ok {
		return x.FeatureIDValue
	}
	return nil
}

func (x *LiteralNodeProto) GetPointValue() *PointProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_PointValue); ok {
		return x.PointValue
	}
	return nil
}

func (x *LiteralNodeProto) GetPathValue() *PolylineProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_PathValue); ok {
		return x.PathValue
	}
	return nil
}

func (x *LiteralNodeProto) GetAreaValue() *MultiPolygonProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_AreaValue); ok {
		return x.AreaValue
	}
	return nil
}

func (x *LiteralNodeProto) GetAppliedChangeValue() *AppliedChangeProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_AppliedChangeValue); ok {
		return x.AppliedChangeValue
	}
	return nil
}

func (x *LiteralNodeProto) GetGeoJSONValue() []byte {
	if x, ok := x.GetValue().(*LiteralNodeProto_GeoJSONValue); ok {
		return x.GeoJSONValue
	}
	return nil
}

func (x *LiteralNodeProto) GetTagValue() *TagProto {
	if x, ok := x.GetValue().(*LiteralNodeProto_TagValue); ok {
		return x.TagValue
	}
	return nil
}

type isLiteralNodeProto_Value interface {
	isLiteralNodeProto_Value()
}

type LiteralNodeProto_NilValue struct {
	NilValue bool `protobuf:"varint,1,opt,name=nilValue,proto3,oneof"`
}

type LiteralNodeProto_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=boolValue,proto3,oneof"`
}

type LiteralNodeProto_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=stringValue,proto3,oneof"`
}

type LiteralNodeProto_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=intValue,proto3,oneof"`
}

type LiteralNodeProto_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,5,opt,name=floatValue,proto3,oneof"`
}

type LiteralNodeProto_CollectionValue struct {
	CollectionValue *CollectionProto `protobuf:"bytes,6,opt,name=collectionValue,proto3,oneof"`
}

type LiteralNodeProto_PairValue struct {
	PairValue *PairProto `protobuf:"bytes,7,opt,name=pairValue,proto3,oneof"`
}

type LiteralNodeProto_FeatureValue struct {
	FeatureValue *FeatureProto `protobuf:"bytes,8,opt,name=featureValue,proto3,oneof"`
}

type LiteralNodeProto_QueryValue struct {
	QueryValue *QueryProto `protobuf:"bytes,9,opt,name=queryValue,proto3,oneof"`
}

type LiteralNodeProto_FeatureIDValue struct {
	FeatureIDValue *FeatureIDProto `protobuf:"bytes,10,opt,name=featureIDValue,proto3,oneof"`
}

type LiteralNodeProto_PointValue struct {
	PointValue *PointProto `protobuf:"bytes,11,opt,name=pointValue,proto3,oneof"`
}

type LiteralNodeProto_PathValue struct {
	PathValue *PolylineProto `protobuf:"bytes,12,opt,name=pathValue,proto3,oneof"`
}

type LiteralNodeProto_AreaValue struct {
	AreaValue *MultiPolygonProto `protobuf:"bytes,13,opt,name=areaValue,proto3,oneof"`
}

type LiteralNodeProto_AppliedChangeValue struct {
	AppliedChangeValue *AppliedChangeProto `protobuf:"bytes,14,opt,name=appliedChangeValue,proto3,oneof"`
}

type LiteralNodeProto_GeoJSONValue struct {
	GeoJSONValue []byte `protobuf:"bytes,15,opt,name=geoJSONValue,proto3,oneof"` // gzipped
}

type LiteralNodeProto_TagValue struct {
	TagValue *TagProto `protobuf:"bytes,16,opt,name=tagValue,proto3,oneof"`
}

func (*LiteralNodeProto_NilValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_BoolValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_StringValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_IntValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_FloatValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_CollectionValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_PairValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_FeatureValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_QueryValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_FeatureIDValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_PointValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_PathValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_AreaValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_AppliedChangeValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_GeoJSONValue) isLiteralNodeProto_Value() {}

func (*LiteralNodeProto_TagValue) isLiteralNodeProto_Value() {}

type CallNodeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function  *NodeProto   `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Args      []*NodeProto `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Pipelined bool         `protobuf:"varint,3,opt,name=pipelined,proto3" json:"pipelined,omitempty"`
}

func (x *CallNodeProto) Reset() {
	*x = CallNodeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallNodeProto) ProtoMessage() {}

func (x *CallNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallNodeProto.ProtoReflect.Descriptor instead.
func (*CallNodeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *CallNodeProto) GetFunction() *NodeProto {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *CallNodeProto) GetArgs() []*NodeProto {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CallNodeProto) GetPipelined() bool {
	if x != nil {
		return x.Pipelined
	}
	return false
}

type LambdaNodeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []string   `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Node *NodeProto `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *LambdaNodeProto) Reset() {
	*x = LambdaNodeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LambdaNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LambdaNodeProto) ProtoMessage() {}

func (x *LambdaNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LambdaNodeProto.ProtoReflect.Descriptor instead.
func (*LambdaNodeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *LambdaNodeProto) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *LambdaNodeProto) GetNode() *NodeProto {
	if x != nil {
		return x.Node
	}
	return nil
}

type KeyQueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KeyQueryProto) Reset() {
	*x = KeyQueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyQueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyQueryProto) ProtoMessage() {}

func (x *KeyQueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyQueryProto.ProtoReflect.Descriptor instead.
func (*KeyQueryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *KeyQueryProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KeyValueQueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValueQueryProto) Reset() {
	*x = KeyValueQueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValueQueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueQueryProto) ProtoMessage() {}

func (x *KeyValueQueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueQueryProto.ProtoReflect.Descriptor instead.
func (*KeyValueQueryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *KeyValueQueryProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueQueryProto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TypedQueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  FeatureType `protobuf:"varint,1,opt,name=type,proto3,enum=features.FeatureType" json:"type,omitempty"`
	Query *QueryProto `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *TypedQueryProto) Reset() {
	*x = TypedQueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypedQueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedQueryProto) ProtoMessage() {}

func (x *TypedQueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedQueryProto.ProtoReflect.Descriptor instead.
func (*TypedQueryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *TypedQueryProto) GetType() FeatureType {
	if x != nil {
		return x.Type
	}
	return FeatureType_FeatureTypePoint
}

func (x *TypedQueryProto) GetQuery() *QueryProto {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueriesProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*QueryProto `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *QueriesProto) Reset() {
	*x = QueriesProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueriesProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueriesProto) ProtoMessage() {}

func (x *QueriesProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueriesProto.ProtoReflect.Descriptor instead.
func (*QueriesProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *QueriesProto) GetQueries() []*QueryProto {
	if x != nil {
		return x.Queries
	}
	return nil
}

type AllQueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllQueryProto) Reset() {
	*x = AllQueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllQueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllQueryProto) ProtoMessage() {}

func (x *AllQueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllQueryProto.ProtoReflect.Descriptor instead.
func (*AllQueryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

type EmptyQueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyQueryProto) Reset() {
	*x = EmptyQueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyQueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyQueryProto) ProtoMessage() {}

func (x *EmptyQueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyQueryProto.ProtoReflect.Descriptor instead.
func (*EmptyQueryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

type CapProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Center       *PointProto `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusMeters float64     `protobuf:"fixed64,2,opt,name=radiusMeters,proto3" json:"radiusMeters,omitempty"`
}

func (x *CapProto) Reset() {
	*x = CapProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapProto) ProtoMessage() {}

func (x *CapProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapProto.ProtoReflect.Descriptor instead.
func (*CapProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *CapProto) GetCenter() *PointProto {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *CapProto) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

type S2CellIDsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S2CellIDs []uint64 `protobuf:"varint,1,rep,packed,name=s2CellIDs,proto3" json:"s2CellIDs,omitempty"`
}

func (x *S2CellIDsProto) Reset() {
	*x = S2CellIDsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CellIDsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CellIDsProto) ProtoMessage() {}

func (x *S2CellIDsProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CellIDsProto.ProtoReflect.Descriptor instead.
func (*S2CellIDsProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *S2CellIDsProto) GetS2CellIDs() []uint64 {
	if x != nil {
		return x.S2CellIDs
	}
	return nil
}

type QueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Query:
	//	*QueryProto_All
	//	*QueryProto_Empty
	//	*QueryProto_Keyed
	//	*QueryProto_Tagged
	//	*QueryProto_Typed
	//	*QueryProto_Intersection
	//	*QueryProto_Union
	//	*QueryProto_IntersectsCap
	//	*QueryProto_IntersectsFeature
	//	*QueryProto_IntersectsPoint
	//	*QueryProto_IntersectsPolyline
	//	*QueryProto_IntersectsMultiPolygon
	//	*QueryProto_IntersectsCells
	//	*QueryProto_MightIntersect
	Query isQueryProto_Query `protobuf_oneof:"query"`
}

func (x *QueryProto) Reset() {
	*x = QueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProto) ProtoMessage() {}

func (x *QueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProto.ProtoReflect.Descriptor instead.
func (*QueryProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (m *QueryProto) GetQuery() isQueryProto_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (x *QueryProto) GetAll() *AllQueryProto {
	if x, ok := x.GetQuery().(*QueryProto_All); ok {
		return x.All
	}
	return nil
}

func (x *QueryProto) GetEmpty() *EmptyQueryProto {
	if x, ok := x.GetQuery().(*QueryProto_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *QueryProto) GetKeyed() string {
	if x, ok := x.GetQuery().(*QueryProto_Keyed); ok {
		return x.Keyed
	}
	return ""
}

func (x *QueryProto) GetTagged() *TagProto {
	if x, ok := x.GetQuery().(*QueryProto_Tagged); ok {
		return x.Tagged
	}
	return nil
}

func (x *QueryProto) GetTyped() *TypedQueryProto {
	if x, ok := x.GetQuery().(*QueryProto_Typed); ok {
		return x.Typed
	}
	return nil
}

func (x *QueryProto) GetIntersection() *QueriesProto {
	if x, ok := x.GetQuery().(*QueryProto_Intersection); ok {
		return x.Intersection
	}
	return nil
}

func (x *QueryProto) GetUnion() *QueriesProto {
	if x, ok := x.GetQuery().(*QueryProto_Union); ok {
		return x.Union
	}
	return nil
}

func (x *QueryProto) GetIntersectsCap() *CapProto {
	if x, ok := x.GetQuery().(*QueryProto_IntersectsCap); ok {
		return x.IntersectsCap
	}
	return nil
}

func (x *QueryProto) GetIntersectsFeature() *FeatureIDProto {
	if x, ok := x.GetQuery().(*QueryProto_IntersectsFeature); ok {
		return x.IntersectsFeature
	}
	return nil
}

func (x *QueryProto) GetIntersectsPoint() *PointProto {
	if x, ok := x.GetQuery().(*QueryProto_IntersectsPoint); ok {
		return x.IntersectsPoint
	}
	return nil
}

func (x *QueryProto) GetIntersectsPolyline() *PolylineProto {
	if x, ok := x.GetQuery().(*QueryProto_IntersectsPolyline); ok {
		return x.IntersectsPolyline
	}
	return nil
}

func (x *QueryProto) GetIntersectsMultiPolygon() *MultiPolygonProto {
	if x, ok := x.GetQuery().(*QueryProto_IntersectsMultiPolygon); ok {
		return x.IntersectsMultiPolygon
	}
	return nil
}

func (x *QueryProto) GetIntersectsCells() *S2CellIDsProto {
	if x, ok := x.GetQuery().(*QueryProto_IntersectsCells); ok {
		return x.IntersectsCells
	}
	return nil
}

func (x *QueryProto) GetMightIntersect() *S2CellIDsProto {
	if x, ok := x.GetQuery().(*QueryProto_MightIntersect); ok {
		return x.MightIntersect
	}
	return nil
}

type isQueryProto_Query interface {
	isQueryProto_Query()
}

type QueryProto_All struct {
	All *AllQueryProto `protobuf:"bytes,1,opt,name=all,proto3,oneof"`
}

type QueryProto_Empty struct {
	Empty *EmptyQueryProto `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type QueryProto_Keyed struct {
	Keyed string `protobuf:"bytes,3,opt,name=keyed,proto3,oneof"`
}

type QueryProto_Tagged struct {
	Tagged *TagProto `protobuf:"bytes,4,opt,name=tagged,proto3,oneof"`
}

type QueryProto_Typed struct {
	Typed *TypedQueryProto `protobuf:"bytes,5,opt,name=typed,proto3,oneof"`
}

type QueryProto_Intersection struct {
	Intersection *QueriesProto `protobuf:"bytes,6,opt,name=intersection,proto3,oneof"`
}

type QueryProto_Union struct {
	Union *QueriesProto `protobuf:"bytes,7,opt,name=union,proto3,oneof"`
}

type QueryProto_IntersectsCap struct {
	IntersectsCap *CapProto `protobuf:"bytes,8,opt,name=intersectsCap,proto3,oneof"`
}

type QueryProto_IntersectsFeature struct {
	IntersectsFeature *FeatureIDProto `protobuf:"bytes,9,opt,name=intersectsFeature,proto3,oneof"`
}

type QueryProto_IntersectsPoint struct {
	IntersectsPoint *PointProto `protobuf:"bytes,10,opt,name=intersectsPoint,proto3,oneof"`
}

type QueryProto_IntersectsPolyline struct {
	IntersectsPolyline *PolylineProto `protobuf:"bytes,11,opt,name=intersectsPolyline,proto3,oneof"`
}

type QueryProto_IntersectsMultiPolygon struct {
	IntersectsMultiPolygon *MultiPolygonProto `protobuf:"bytes,12,opt,name=intersectsMultiPolygon,proto3,oneof"`
}

type QueryProto_IntersectsCells struct {
	IntersectsCells *S2CellIDsProto `protobuf:"bytes,13,opt,name=intersectsCells,proto3,oneof"`
}

type QueryProto_MightIntersect struct {
	MightIntersect *S2CellIDsProto `protobuf:"bytes,14,opt,name=mightIntersect,proto3,oneof"`
}

func (*QueryProto_All) isQueryProto_Query() {}

func (*QueryProto_Empty) isQueryProto_Query() {}

func (*QueryProto_Keyed) isQueryProto_Query() {}

func (*QueryProto_Tagged) isQueryProto_Query() {}

func (*QueryProto_Typed) isQueryProto_Query() {}

func (*QueryProto_Intersection) isQueryProto_Query() {}

func (*QueryProto_Union) isQueryProto_Query() {}

func (*QueryProto_IntersectsCap) isQueryProto_Query() {}

func (*QueryProto_IntersectsFeature) isQueryProto_Query() {}

func (*QueryProto_IntersectsPoint) isQueryProto_Query() {}

func (*QueryProto_IntersectsPolyline) isQueryProto_Query() {}

func (*QueryProto_IntersectsMultiPolygon) isQueryProto_Query() {}

func (*QueryProto_IntersectsCells) isQueryProto_Query() {}

func (*QueryProto_MightIntersect) isQueryProto_Query() {}

type FindFeatureByIDRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *FeatureIDProto `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindFeatureByIDRequestProto) Reset() {
	*x = FindFeatureByIDRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFeatureByIDRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFeatureByIDRequestProto) ProtoMessage() {}

func (x *FindFeatureByIDRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFeatureByIDRequestProto.ProtoReflect.Descriptor instead.
func (*FindFeatureByIDRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *FindFeatureByIDRequestProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

type FindFeatureByIDResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feature *FeatureProto `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
}

func (x *FindFeatureByIDResponseProto) Reset() {
	*x = FindFeatureByIDResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFeatureByIDResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFeatureByIDResponseProto) ProtoMessage() {}

func (x *FindFeatureByIDResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFeatureByIDResponseProto.ProtoReflect.Descriptor instead.
func (*FindFeatureByIDResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *FindFeatureByIDResponseProto) GetFeature() *FeatureProto {
	if x != nil {
		return x.Feature
	}
	return nil
}

type FindFeaturesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *QueryProto `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *FindFeaturesRequestProto) Reset() {
	*x = FindFeaturesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFeaturesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFeaturesRequestProto) ProtoMessage() {}

func (x *FindFeaturesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFeaturesRequestProto.ProtoReflect.Descriptor instead.
func (*FindFeaturesRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *FindFeaturesRequestProto) GetQuery() *QueryProto {
	if x != nil {
		return x.Query
	}
	return nil
}

type FindFeaturesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []*FeatureProto `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *FindFeaturesResponseProto) Reset() {
	*x = FindFeaturesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFeaturesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFeaturesResponseProto) ProtoMessage() {}

func (x *FindFeaturesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFeaturesResponseProto.ProtoReflect.Descriptor instead.
func (*FindFeaturesResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *FindFeaturesResponseProto) GetFeatures() []*FeatureProto {
	if x != nil {
		return x.Features
	}
	return nil
}

type ModifyTagsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *FeatureIDProto `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags []*TagProto     `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ModifyTagsRequestProto) Reset() {
	*x = ModifyTagsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyTagsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTagsRequestProto) ProtoMessage() {}

func (x *ModifyTagsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTagsRequestProto.ProtoReflect.Descriptor instead.
func (*ModifyTagsRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *ModifyTagsRequestProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ModifyTagsRequestProto) GetTags() []*TagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ModifyTagsBatchRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*ModifyTagsRequestProto `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *ModifyTagsBatchRequestProto) Reset() {
	*x = ModifyTagsBatchRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyTagsBatchRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTagsBatchRequestProto) ProtoMessage() {}

func (x *ModifyTagsBatchRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTagsBatchRequestProto.ProtoReflect.Descriptor instead.
func (*ModifyTagsBatchRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *ModifyTagsBatchRequestProto) GetRequests() []*ModifyTagsRequestProto {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ModifyTagsBatchResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModifyTagsBatchResponseProto) Reset() {
	*x = ModifyTagsBatchResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyTagsBatchResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTagsBatchResponseProto) ProtoMessage() {}

func (x *ModifyTagsBatchResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTagsBatchResponseProto.ProtoReflect.Descriptor instead.
func (*ModifyTagsBatchResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

type EvaluateRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *NodeProto `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Version string     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *EvaluateRequestProto) Reset() {
	*x = EvaluateRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequestProto) ProtoMessage() {}

func (x *EvaluateRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequestProto.ProtoReflect.Descriptor instead.
func (*EvaluateRequestProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *EvaluateRequestProto) GetRequest() *NodeProto {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *EvaluateRequestProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type EvaluateResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *NodeProto `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *EvaluateResponseProto) Reset() {
	*x = EvaluateResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponseProto) ProtoMessage() {}

func (x *EvaluateResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponseProto.ProtoReflect.Descriptor instead.
func (*EvaluateResponseProto) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *EvaluateResponseProto) GetResult() *NodeProto {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x1a, 0x0e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6b, 0x0a, 0x0f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x29, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x2d,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x67, 0x0a,
	0x09, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x43, 0x0a, 0x15, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x2a, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49,
	0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x12,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x34, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0xe3,
	0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x31, 0x0a, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00,
	0x52, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x61, 0x6c,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x63,
	0x61, 0x6c, 0x6c, 0x12, 0x2f, 0x0a, 0x07, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x5f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x61,
	0x6d, 0x62, 0x64, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x6e,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x42, 0x06, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x22, 0xb5, 0x06, 0x0a, 0x10, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c,
	0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x08, 0x6e, 0x69, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6e,
	0x69, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a,
	0x09, 0x70, 0x61, 0x69, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x48, 0x00, 0x52, 0x09, 0x70, 0x61, 0x69, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3c, 0x0a,
	0x0c, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x48, 0x00, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x42,
	0x0a, 0x0e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x48, 0x00, 0x52, 0x0e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0a,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x61,
	0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x6e,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x70, 0x61, 0x74, 0x68, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x61, 0x72, 0x65, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x49, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0c, 0x67,
	0x65, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x65, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54,
	0x61, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x74, 0x61, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7d, 0x0a, 0x0d,
	0x43, 0x61, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x22, 0x49, 0x0a, 0x0f, 0x4c,
	0x61, 0x6d, 0x62, 0x64, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3c, 0x0a, 0x12, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x63, 0x0a, 0x0f, 0x54, 0x79, 0x70, 0x65, 0x64,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x39, 0x0a, 0x0c,
	0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x0a, 0x07,
	0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07,
	0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x08, 0x43,
	0x61, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x4d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x72, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x2e, 0x0a, 0x0e, 0x53, 0x32, 0x43,
	0x65, 0x6c, 0x6c, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x32, 0x43, 0x65, 0x6c, 0x6c, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x32, 0x43, 0x65, 0x6c, 0x6c, 0x49, 0x44, 0x73, 0x22, 0xa8, 0x06, 0x0a, 0x0a, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x12, 0x2c, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x16,
	0x0a, 0x05, 0x6b, 0x65, 0x79, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x6b, 0x65, 0x79, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x54, 0x61, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x74, 0x61,
	0x67, 0x67, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x64, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x74, 0x79, 0x70,
	0x65, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52,
	0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x65, 0x63, 0x74, 0x73, 0x43, 0x61, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x43, 0x61, 0x70, 0x12, 0x48, 0x0a,
	0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x48, 0x00, 0x52, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x65, 0x63, 0x74, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x65, 0x63, 0x74, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x49, 0x0a, 0x12, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x50, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00,
	0x52, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x50, 0x6f, 0x6c, 0x79,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x55, 0x0a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63,
	0x74, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x48, 0x00, 0x52, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x32, 0x43, 0x65, 0x6c,
	0x6c, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x73, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x3d, 0x0a, 0x0e,
	0x6d, 0x69, 0x67, 0x68, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x32, 0x43, 0x65, 0x6c,
	0x6c, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x69, 0x67,
	0x68, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x47, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a,
	0x1c, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x0a,
	0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x41, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x22, 0x4f, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x32, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x16, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x61, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2e, 0x54, 0x61, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22,
	0x56, 0x0a, 0x1b, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x61, 0x67, 0x73, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x37,
	0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x61, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x54, 0x61, 0x67, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x14, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x15, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x47, 0x0a, 0x02, 0x42, 0x36, 0x12, 0x41, 0x0a, 0x08, 0x45, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x19, 0x5a,
	0x17, 0x64, 0x69, 0x61, 0x67, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f,
	0x62, 0x36, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_proto_goTypes = []interface{}{
	(*CollectionProto)(nil),              // 0: api.CollectionProto
	(*PairProto)(nil),                    // 1: api.PairProto
	(*ModifiedFeaturesProto)(nil),        // 2: api.ModifiedFeaturesProto
	(*AppliedChangeProto)(nil),           // 3: api.AppliedChangeProto
	(*NodeProto)(nil),                    // 4: api.NodeProto
	(*LiteralNodeProto)(nil),             // 5: api.LiteralNodeProto
	(*CallNodeProto)(nil),                // 6: api.CallNodeProto
	(*LambdaNodeProto)(nil),              // 7: api.LambdaNodeProto
	(*KeyQueryProto)(nil),                // 8: api.KeyQueryProto
	(*KeyValueQueryProto)(nil),           // 9: api.KeyValueQueryProto
	(*TypedQueryProto)(nil),              // 10: api.TypedQueryProto
	(*QueriesProto)(nil),                 // 11: api.QueriesProto
	(*AllQueryProto)(nil),                // 12: api.AllQueryProto
	(*EmptyQueryProto)(nil),              // 13: api.EmptyQueryProto
	(*CapProto)(nil),                     // 14: api.CapProto
	(*S2CellIDsProto)(nil),               // 15: api.S2CellIDsProto
	(*QueryProto)(nil),                   // 16: api.QueryProto
	(*FindFeatureByIDRequestProto)(nil),  // 17: api.FindFeatureByIDRequestProto
	(*FindFeatureByIDResponseProto)(nil), // 18: api.FindFeatureByIDResponseProto
	(*FindFeaturesRequestProto)(nil),     // 19: api.FindFeaturesRequestProto
	(*FindFeaturesResponseProto)(nil),    // 20: api.FindFeaturesResponseProto
	(*ModifyTagsRequestProto)(nil),       // 21: api.ModifyTagsRequestProto
	(*ModifyTagsBatchRequestProto)(nil),  // 22: api.ModifyTagsBatchRequestProto
	(*ModifyTagsBatchResponseProto)(nil), // 23: api.ModifyTagsBatchResponseProto
	(*EvaluateRequestProto)(nil),         // 24: api.EvaluateRequestProto
	(*EvaluateResponseProto)(nil),        // 25: api.EvaluateResponseProto
	(*FeatureIDProto)(nil),               // 26: features.FeatureIDProto
	(*FeatureProto)(nil),                 // 27: features.FeatureProto
	(*PointProto)(nil),                   // 28: geometry.PointProto
	(*PolylineProto)(nil),                // 29: geometry.PolylineProto
	(*MultiPolygonProto)(nil),            // 30: geometry.MultiPolygonProto
	(*TagProto)(nil),                     // 31: features.TagProto
	(FeatureType)(0),                     // 32: features.FeatureType
}
var file_api_proto_depIdxs = []int32{
	5,  // 0: api.CollectionProto.keys:type_name -> api.LiteralNodeProto
	5,  // 1: api.CollectionProto.values:type_name -> api.LiteralNodeProto
	5,  // 2: api.PairProto.first:type_name -> api.LiteralNodeProto
	5,  // 3: api.PairProto.second:type_name -> api.LiteralNodeProto
	26, // 4: api.ModifiedFeaturesProto.ids:type_name -> features.FeatureIDProto
	26, // 5: api.AppliedChangeProto.original:type_name -> features.FeatureIDProto
	26, // 6: api.AppliedChangeProto.modified:type_name -> features.FeatureIDProto
	5,  // 7: api.NodeProto.literal:type_name -> api.LiteralNodeProto
	6,  // 8: api.NodeProto.call:type_name -> api.CallNodeProto
	7,  // 9: api.NodeProto.lambda_:type_name -> api.LambdaNodeProto
	0,  // 10: api.LiteralNodeProto.collectionValue:type_name -> api.CollectionProto
	1,  // 11: api.LiteralNodeProto.pairValue:type_name -> api.PairProto
	27, // 12: api.LiteralNodeProto.featureValue:type_name -> features.FeatureProto
	16, // 13: api.LiteralNodeProto.queryValue:type_name -> api.QueryProto
	26, // 14: api.LiteralNodeProto.featureIDValue:type_name -> features.FeatureIDProto
	28, // 15: api.LiteralNodeProto.pointValue:type_name -> geometry.PointProto
	29, // 16: api.LiteralNodeProto.pathValue:type_name -> geometry.PolylineProto
	30, // 17: api.LiteralNodeProto.areaValue:type_name -> geometry.MultiPolygonProto
	3,  // 18: api.LiteralNodeProto.appliedChangeValue:type_name -> api.AppliedChangeProto
	31, // 19: api.LiteralNodeProto.tagValue:type_name -> features.TagProto
	4,  // 20: api.CallNodeProto.function:type_name -> api.NodeProto
	4,  // 21: api.CallNodeProto.args:type_name -> api.NodeProto
	4,  // 22: api.LambdaNodeProto.node:type_name -> api.NodeProto
	32, // 23: api.TypedQueryProto.type:type_name -> features.FeatureType
	16, // 24: api.TypedQueryProto.query:type_name -> api.QueryProto
	16, // 25: api.QueriesProto.queries:type_name -> api.QueryProto
	28, // 26: api.CapProto.center:type_name -> geometry.PointProto
	12, // 27: api.QueryProto.all:type_name -> api.AllQueryProto
	13, // 28: api.QueryProto.empty:type_name -> api.EmptyQueryProto
	31, // 29: api.QueryProto.tagged:type_name -> features.TagProto
	10, // 30: api.QueryProto.typed:type_name -> api.TypedQueryProto
	11, // 31: api.QueryProto.intersection:type_name -> api.QueriesProto
	11, // 32: api.QueryProto.union:type_name -> api.QueriesProto
	14, // 33: api.QueryProto.intersectsCap:type_name -> api.CapProto
	26, // 34: api.QueryProto.intersectsFeature:type_name -> features.FeatureIDProto
	28, // 35: api.QueryProto.intersectsPoint:type_name -> geometry.PointProto
	29, // 36: api.QueryProto.intersectsPolyline:type_name -> geometry.PolylineProto
	30, // 37: api.QueryProto.intersectsMultiPolygon:type_name -> geometry.MultiPolygonProto
	15, // 38: api.QueryProto.intersectsCells:type_name -> api.S2CellIDsProto
	15, // 39: api.QueryProto.mightIntersect:type_name -> api.S2CellIDsProto
	26, // 40: api.FindFeatureByIDRequestProto.id:type_name -> features.FeatureIDProto
	27, // 41: api.FindFeatureByIDResponseProto.feature:type_name -> features.FeatureProto
	16, // 42: api.FindFeaturesRequestProto.query:type_name -> api.QueryProto
	27, // 43: api.FindFeaturesResponseProto.features:type_name -> features.FeatureProto
	26, // 44: api.ModifyTagsRequestProto.id:type_name -> features.FeatureIDProto
	31, // 45: api.ModifyTagsRequestProto.tags:type_name -> features.TagProto
	21, // 46: api.ModifyTagsBatchRequestProto.requests:type_name -> api.ModifyTagsRequestProto
	4,  // 47: api.EvaluateRequestProto.request:type_name -> api.NodeProto
	4,  // 48: api.EvaluateResponseProto.result:type_name -> api.NodeProto
	24, // 49: api.B6.Evaluate:input_type -> api.EvaluateRequestProto
	25, // 50: api.B6.Evaluate:output_type -> api.EvaluateResponseProto
	50, // [50:51] is the sub-list for method output_type
	49, // [49:50] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_geometry_proto_init()
	file_features_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifiedFeaturesProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppliedChangeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiteralNodeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallNodeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LambdaNodeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyQueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValueQueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypedQueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueriesProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllQueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyQueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CellIDsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFeatureByIDRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFeatureByIDResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFeaturesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFeaturesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyTagsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyTagsBatchRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyTagsBatchResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*NodeProto_Symbol)(nil),
		(*NodeProto_Literal)(nil),
		(*NodeProto_Call)(nil),
		(*NodeProto_Lambda_)(nil),
	}
	file_api_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*LiteralNodeProto_NilValue)(nil),
		(*LiteralNodeProto_BoolValue)(nil),
		(*LiteralNodeProto_StringValue)(nil),
		(*LiteralNodeProto_IntValue)(nil),
		(*LiteralNodeProto_FloatValue)(nil),
		(*LiteralNodeProto_CollectionValue)(nil),
		(*LiteralNodeProto_PairValue)(nil),
		(*LiteralNodeProto_FeatureValue)(nil),
		(*LiteralNodeProto_QueryValue)(nil),
		(*LiteralNodeProto_FeatureIDValue)(nil),
		(*LiteralNodeProto_PointValue)(nil),
		(*LiteralNodeProto_PathValue)(nil),
		(*LiteralNodeProto_AreaValue)(nil),
		(*LiteralNodeProto_AppliedChangeValue)(nil),
		(*LiteralNodeProto_GeoJSONValue)(nil),
		(*LiteralNodeProto_TagValue)(nil),
	}
	file_api_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*QueryProto_All)(nil),
		(*QueryProto_Empty)(nil),
		(*QueryProto_Keyed)(nil),
		(*QueryProto_Tagged)(nil),
		(*QueryProto_Typed)(nil),
		(*QueryProto_Intersection)(nil),
		(*QueryProto_Union)(nil),
		(*QueryProto_IntersectsCap)(nil),
		(*QueryProto_IntersectsFeature)(nil),
		(*QueryProto_IntersectsPoint)(nil),
		(*QueryProto_IntersectsPolyline)(nil),
		(*QueryProto_IntersectsMultiPolygon)(nil),
		(*QueryProto_IntersectsCells)(nil),
		(*QueryProto_MightIntersect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
