// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: features.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureType int32

const (
	FeatureType_FeatureTypePoint    FeatureType = 0
	FeatureType_FeatureTypePath     FeatureType = 1
	FeatureType_FeatureTypeArea     FeatureType = 2
	FeatureType_FeatureTypeRelation FeatureType = 3
	FeatureType_FeatureTypeInvalid  FeatureType = 4
)

// Enum value maps for FeatureType.
var (
	FeatureType_name = map[int32]string{
		0: "FeatureTypePoint",
		1: "FeatureTypePath",
		2: "FeatureTypeArea",
		3: "FeatureTypeRelation",
		4: "FeatureTypeInvalid",
	}
	FeatureType_value = map[string]int32{
		"FeatureTypePoint":    0,
		"FeatureTypePath":     1,
		"FeatureTypeArea":     2,
		"FeatureTypeRelation": 3,
		"FeatureTypeInvalid":  4,
	}
)

func (x FeatureType) Enum() *FeatureType {
	p := new(FeatureType)
	*p = x
	return p
}

func (x FeatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_features_proto_enumTypes[0].Descriptor()
}

func (FeatureType) Type() protoreflect.EnumType {
	return &file_features_proto_enumTypes[0]
}

func (x FeatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureType.Descriptor instead.
func (FeatureType) EnumDescriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

type TagProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TagProto) Reset() {
	*x = TagProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagProto) ProtoMessage() {}

func (x *TagProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagProto.ProtoReflect.Descriptor instead.
func (*TagProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

func (x *TagProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TagProto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FeatureIDProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      FeatureType `protobuf:"varint,1,opt,name=type,proto3,enum=features.FeatureType" json:"type,omitempty"`
	Namespace string      `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value     uint64      `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FeatureIDProto) Reset() {
	*x = FeatureIDProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureIDProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureIDProto) ProtoMessage() {}

func (x *FeatureIDProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureIDProto.ProtoReflect.Descriptor instead.
func (*FeatureIDProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureIDProto) GetType() FeatureType {
	if x != nil {
		return x.Type
	}
	return FeatureType_FeatureTypePoint
}

func (x *FeatureIDProto) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FeatureIDProto) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PointFeatureProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *FeatureIDProto `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags  []*TagProto     `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Point *PointProto     `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *PointFeatureProto) Reset() {
	*x = PointFeatureProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointFeatureProto) ProtoMessage() {}

func (x *PointFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointFeatureProto.ProtoReflect.Descriptor instead.
func (*PointFeatureProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{2}
}

func (x *PointFeatureProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PointFeatureProto) GetTags() []*TagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PointFeatureProto) GetPoint() *PointProto {
	if x != nil {
		return x.Point
	}
	return nil
}

type PathFeatureProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *FeatureIDProto      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags         []*TagProto          `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Features     []*PointFeatureProto `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	LengthMeters float64              `protobuf:"fixed64,4,opt,name=lengthMeters,proto3" json:"lengthMeters,omitempty"`
}

func (x *PathFeatureProto) Reset() {
	*x = PathFeatureProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathFeatureProto) ProtoMessage() {}

func (x *PathFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathFeatureProto.ProtoReflect.Descriptor instead.
func (*PathFeatureProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{3}
}

func (x *PathFeatureProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PathFeatureProto) GetTags() []*TagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PathFeatureProto) GetFeatures() []*PointFeatureProto {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PathFeatureProto) GetLengthMeters() float64 {
	if x != nil {
		return x.LengthMeters
	}
	return 0
}

type PathFeaturesProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*PathFeatureProto `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *PathFeaturesProto) Reset() {
	*x = PathFeaturesProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathFeaturesProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathFeaturesProto) ProtoMessage() {}

func (x *PathFeaturesProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathFeaturesProto.ProtoReflect.Descriptor instead.
func (*PathFeaturesProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{4}
}

func (x *PathFeaturesProto) GetPaths() []*PathFeatureProto {
	if x != nil {
		return x.Paths
	}
	return nil
}

type AreaFeatureProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *FeatureIDProto      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags     []*TagProto          `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Features []*PathFeaturesProto `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *AreaFeatureProto) Reset() {
	*x = AreaFeatureProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaFeatureProto) ProtoMessage() {}

func (x *AreaFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaFeatureProto.ProtoReflect.Descriptor instead.
func (*AreaFeatureProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{5}
}

func (x *AreaFeatureProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AreaFeatureProto) GetTags() []*TagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AreaFeatureProto) GetFeatures() []*PathFeaturesProto {
	if x != nil {
		return x.Features
	}
	return nil
}

type RelationMemberProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *FeatureIDProto `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role string          `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *RelationMemberProto) Reset() {
	*x = RelationMemberProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationMemberProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationMemberProto) ProtoMessage() {}

func (x *RelationMemberProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationMemberProto.ProtoReflect.Descriptor instead.
func (*RelationMemberProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{6}
}

func (x *RelationMemberProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RelationMemberProto) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RelationFeatureProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *FeatureIDProto        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags    []*TagProto            `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Members []*RelationMemberProto `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *RelationFeatureProto) Reset() {
	*x = RelationFeatureProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationFeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFeatureProto) ProtoMessage() {}

func (x *RelationFeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFeatureProto.ProtoReflect.Descriptor instead.
func (*RelationFeatureProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{7}
}

func (x *RelationFeatureProto) GetId() *FeatureIDProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RelationFeatureProto) GetTags() []*TagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RelationFeatureProto) GetMembers() []*RelationMemberProto {
	if x != nil {
		return x.Members
	}
	return nil
}

type FeatureProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Feature:
	//	*FeatureProto_Point
	//	*FeatureProto_Path
	//	*FeatureProto_Area
	//	*FeatureProto_Relation
	Feature isFeatureProto_Feature `protobuf_oneof:"feature"`
}

func (x *FeatureProto) Reset() {
	*x = FeatureProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureProto) ProtoMessage() {}

func (x *FeatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureProto.ProtoReflect.Descriptor instead.
func (*FeatureProto) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{8}
}

func (m *FeatureProto) GetFeature() isFeatureProto_Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (x *FeatureProto) GetPoint() *PointFeatureProto {
	if x, ok := x.GetFeature().(*FeatureProto_Point); ok {
		return x.Point
	}
	return nil
}

func (x *FeatureProto) GetPath() *PathFeatureProto {
	if x, ok := x.GetFeature().(*FeatureProto_Path); ok {
		return x.Path
	}
	return nil
}

func (x *FeatureProto) GetArea() *AreaFeatureProto {
	if x, ok := x.GetFeature().(*FeatureProto_Area); ok {
		return x.Area
	}
	return nil
}

func (x *FeatureProto) GetRelation() *RelationFeatureProto {
	if x, ok := x.GetFeature().(*FeatureProto_Relation); ok {
		return x.Relation
	}
	return nil
}

type isFeatureProto_Feature interface {
	isFeatureProto_Feature()
}

type FeatureProto_Point struct {
	Point *PointFeatureProto `protobuf:"bytes,1,opt,name=point,proto3,oneof"`
}

type FeatureProto_Path struct {
	Path *PathFeatureProto `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

type FeatureProto_Area struct {
	Area *AreaFeatureProto `protobuf:"bytes,3,opt,name=area,proto3,oneof"`
}

type FeatureProto_Relation struct {
	Relation *RelationFeatureProto `protobuf:"bytes,4,opt,name=relation,proto3,oneof"`
}

func (*FeatureProto_Point) isFeatureProto_Feature() {}

func (*FeatureProto_Path) isFeatureProto_Feature() {}

func (*FeatureProto_Area) isFeatureProto_Feature() {}

func (*FeatureProto_Relation) isFeatureProto_Feature() {}

var File_features_proto protoreflect.FileDescriptor

var file_features_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x0e, 0x67, 0x65, 0x6f, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x08, 0x54, 0x61,
	0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6f,
	0x0a, 0x0e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x91, 0x01, 0x0a, 0x11, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x26, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x74, 0x68, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x45, 0x0a, 0x11, 0x50, 0x61, 0x74, 0x68, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0x9d,
	0x01, 0x0a, 0x10, 0x41, 0x72, 0x65, 0x61, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x53,
	0x0a, 0x13, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x54, 0x61, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x37,
	0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0xf0, 0x01, 0x0a, 0x0c, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x33, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x30, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x30, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x12, 0x3c, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x09, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2a, 0x7e, 0x0a, 0x0b, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x41, 0x72, 0x65, 0x61, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x04, 0x42, 0x19, 0x5a, 0x17, 0x64, 0x69,
	0x61, 0x67, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x36, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_features_proto_rawDescOnce sync.Once
	file_features_proto_rawDescData = file_features_proto_rawDesc
)

func file_features_proto_rawDescGZIP() []byte {
	file_features_proto_rawDescOnce.Do(func() {
		file_features_proto_rawDescData = protoimpl.X.CompressGZIP(file_features_proto_rawDescData)
	})
	return file_features_proto_rawDescData
}

var file_features_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_features_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_features_proto_goTypes = []interface{}{
	(FeatureType)(0),             // 0: features.FeatureType
	(*TagProto)(nil),             // 1: features.TagProto
	(*FeatureIDProto)(nil),       // 2: features.FeatureIDProto
	(*PointFeatureProto)(nil),    // 3: features.PointFeatureProto
	(*PathFeatureProto)(nil),     // 4: features.PathFeatureProto
	(*PathFeaturesProto)(nil),    // 5: features.PathFeaturesProto
	(*AreaFeatureProto)(nil),     // 6: features.AreaFeatureProto
	(*RelationMemberProto)(nil),  // 7: features.RelationMemberProto
	(*RelationFeatureProto)(nil), // 8: features.RelationFeatureProto
	(*FeatureProto)(nil),         // 9: features.FeatureProto
	(*PointProto)(nil),           // 10: geometry.PointProto
}
var file_features_proto_depIdxs = []int32{
	0,  // 0: features.FeatureIDProto.type:type_name -> features.FeatureType
	2,  // 1: features.PointFeatureProto.id:type_name -> features.FeatureIDProto
	1,  // 2: features.PointFeatureProto.tags:type_name -> features.TagProto
	10, // 3: features.PointFeatureProto.point:type_name -> geometry.PointProto
	2,  // 4: features.PathFeatureProto.id:type_name -> features.FeatureIDProto
	1,  // 5: features.PathFeatureProto.tags:type_name -> features.TagProto
	3,  // 6: features.PathFeatureProto.features:type_name -> features.PointFeatureProto
	4,  // 7: features.PathFeaturesProto.paths:type_name -> features.PathFeatureProto
	2,  // 8: features.AreaFeatureProto.id:type_name -> features.FeatureIDProto
	1,  // 9: features.AreaFeatureProto.tags:type_name -> features.TagProto
	5,  // 10: features.AreaFeatureProto.features:type_name -> features.PathFeaturesProto
	2,  // 11: features.RelationMemberProto.id:type_name -> features.FeatureIDProto
	2,  // 12: features.RelationFeatureProto.id:type_name -> features.FeatureIDProto
	1,  // 13: features.RelationFeatureProto.tags:type_name -> features.TagProto
	7,  // 14: features.RelationFeatureProto.members:type_name -> features.RelationMemberProto
	3,  // 15: features.FeatureProto.point:type_name -> features.PointFeatureProto
	4,  // 16: features.FeatureProto.path:type_name -> features.PathFeatureProto
	6,  // 17: features.FeatureProto.area:type_name -> features.AreaFeatureProto
	8,  // 18: features.FeatureProto.relation:type_name -> features.RelationFeatureProto
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_features_proto_init() }
func file_features_proto_init() {
	if File_features_proto != nil {
		return
	}
	file_geometry_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_features_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureIDProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointFeatureProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathFeatureProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathFeaturesProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaFeatureProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationMemberProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationFeatureProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_features_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*FeatureProto_Point)(nil),
		(*FeatureProto_Path)(nil),
		(*FeatureProto_Area)(nil),
		(*FeatureProto_Relation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_features_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_features_proto_goTypes,
		DependencyIndexes: file_features_proto_depIdxs,
		EnumInfos:         file_features_proto_enumTypes,
		MessageInfos:      file_features_proto_msgTypes,
	}.Build()
	File_features_proto = out.File
	file_features_proto_rawDesc = nil
	file_features_proto_goTypes = nil
	file_features_proto_depIdxs = nil
}
