// Snapshot of the Mapbox vector tile protocol buffer specification, source:
// https://raw.githubusercontent.com/mapbox/vector-tile-spec/master/2.1/vector_tile.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: tiles.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeomType is described in section 4.3.4 of the specification
type TileProto_GeomType int32

const (
	TileProto_UNKNOWN    TileProto_GeomType = 0
	TileProto_POINT      TileProto_GeomType = 1
	TileProto_LINESTRING TileProto_GeomType = 2
	TileProto_POLYGON    TileProto_GeomType = 3
)

// Enum value maps for TileProto_GeomType.
var (
	TileProto_GeomType_name = map[int32]string{
		0: "UNKNOWN",
		1: "POINT",
		2: "LINESTRING",
		3: "POLYGON",
	}
	TileProto_GeomType_value = map[string]int32{
		"UNKNOWN":    0,
		"POINT":      1,
		"LINESTRING": 2,
		"POLYGON":    3,
	}
)

func (x TileProto_GeomType) Enum() *TileProto_GeomType {
	p := new(TileProto_GeomType)
	*p = x
	return p
}

func (x TileProto_GeomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TileProto_GeomType) Descriptor() protoreflect.EnumDescriptor {
	return file_tiles_proto_enumTypes[0].Descriptor()
}

func (TileProto_GeomType) Type() protoreflect.EnumType {
	return &file_tiles_proto_enumTypes[0]
}

func (x TileProto_GeomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TileProto_GeomType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TileProto_GeomType(num)
	return nil
}

// Deprecated: Use TileProto_GeomType.Descriptor instead.
func (TileProto_GeomType) EnumDescriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0, 0}
}

type TileProto struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	extensionFields protoimpl.ExtensionFields

	Layers []*TileProto_Layer `protobuf:"bytes,3,rep,name=layers" json:"layers,omitempty"`
}

func (x *TileProto) Reset() {
	*x = TileProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileProto) ProtoMessage() {}

func (x *TileProto) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileProto.ProtoReflect.Descriptor instead.
func (*TileProto) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0}
}

var extRange_TileProto = []protoiface.ExtensionRangeV1{
	{Start: 16, End: 8191},
}

// Deprecated: Use TileProto.ProtoReflect.Descriptor.ExtensionRanges instead.
func (*TileProto) ExtensionRangeArray() []protoiface.ExtensionRangeV1 {
	return extRange_TileProto
}

func (x *TileProto) GetLayers() []*TileProto_Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

// Variant type encoding
// The use of values is described in section 4.1 of the specification
type TileProto_Value struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	extensionFields protoimpl.ExtensionFields

	// Exactly one of these values must be present in a valid message
	StringValue *string  `protobuf:"bytes,1,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	FloatValue  *float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue *float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	IntValue    *int64   `protobuf:"varint,4,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	UintValue   *uint64  `protobuf:"varint,5,opt,name=uint_value,json=uintValue" json:"uint_value,omitempty"`
	SintValue   *int64   `protobuf:"zigzag64,6,opt,name=sint_value,json=sintValue" json:"sint_value,omitempty"`
	BoolValue   *bool    `protobuf:"varint,7,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
}

func (x *TileProto_Value) Reset() {
	*x = TileProto_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileProto_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileProto_Value) ProtoMessage() {}

func (x *TileProto_Value) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileProto_Value.ProtoReflect.Descriptor instead.
func (*TileProto_Value) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0, 0}
}

var extRange_TileProto_Value = []protoiface.ExtensionRangeV1{
	{Start: 8, End: 536870911},
}

// Deprecated: Use TileProto_Value.ProtoReflect.Descriptor.ExtensionRanges instead.
func (*TileProto_Value) ExtensionRangeArray() []protoiface.ExtensionRangeV1 {
	return extRange_TileProto_Value
}

func (x *TileProto_Value) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *TileProto_Value) GetFloatValue() float32 {
	if x != nil && x.FloatValue != nil {
		return *x.FloatValue
	}
	return 0
}

func (x *TileProto_Value) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *TileProto_Value) GetIntValue() int64 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *TileProto_Value) GetUintValue() uint64 {
	if x != nil && x.UintValue != nil {
		return *x.UintValue
	}
	return 0
}

func (x *TileProto_Value) GetSintValue() int64 {
	if x != nil && x.SintValue != nil {
		return *x.SintValue
	}
	return 0
}

func (x *TileProto_Value) GetBoolValue() bool {
	if x != nil && x.BoolValue != nil {
		return *x.BoolValue
	}
	return false
}

// Features are described in section 4.2 of the specification
type TileProto_Feature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *uint64 `protobuf:"varint,1,opt,name=id,def=0" json:"id,omitempty"`
	// Tags of this feature are encoded as repeated pairs of
	// integers.
	// A detailed description of tags is located in sections
	// 4.2 and 4.4 of the specification
	Tags []uint32 `protobuf:"varint,2,rep,packed,name=tags" json:"tags,omitempty"`
	// The type of geometry stored in this feature.
	Type *TileProto_GeomType `protobuf:"varint,3,opt,name=type,enum=tiles.TileProto_GeomType,def=0" json:"type,omitempty"`
	// Contains a stream of commands and parameters (vertices).
	// A detailed description on geometry encoding is located in
	// section 4.3 of the specification.
	Geometry []uint32 `protobuf:"varint,4,rep,packed,name=geometry" json:"geometry,omitempty"`
}

// Default values for TileProto_Feature fields.
const (
	Default_TileProto_Feature_Id   = uint64(0)
	Default_TileProto_Feature_Type = TileProto_UNKNOWN
)

func (x *TileProto_Feature) Reset() {
	*x = TileProto_Feature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileProto_Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileProto_Feature) ProtoMessage() {}

func (x *TileProto_Feature) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileProto_Feature.ProtoReflect.Descriptor instead.
func (*TileProto_Feature) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TileProto_Feature) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_TileProto_Feature_Id
}

func (x *TileProto_Feature) GetTags() []uint32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TileProto_Feature) GetType() TileProto_GeomType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_TileProto_Feature_Type
}

func (x *TileProto_Feature) GetGeometry() []uint32 {
	if x != nil {
		return x.Geometry
	}
	return nil
}

// Layers are described in section 4.1 of the specification
type TileProto_Layer struct {
	state           protoimpl.MessageState
	sizeCache       protoimpl.SizeCache
	unknownFields   protoimpl.UnknownFields
	extensionFields protoimpl.ExtensionFields

	// Any compliant implementation must first read the version
	// number encoded in this message and choose the correct
	// implementation for this version number before proceeding to
	// decode other parts of this message.
	Version *uint32 `protobuf:"varint,15,req,name=version,def=1" json:"version,omitempty"`
	Name    *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// The actual features in this tile.
	Features []*TileProto_Feature `protobuf:"bytes,2,rep,name=features" json:"features,omitempty"`
	// Dictionary encoding for keys
	Keys []string `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	// Dictionary encoding for values
	Values []*TileProto_Value `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	// Although this is an "optional" field it is required by the specification.
	// See https://github.com/mapbox/vector-tile-spec/issues/47
	Extent *uint32 `protobuf:"varint,5,opt,name=extent,def=4096" json:"extent,omitempty"`
}

// Default values for TileProto_Layer fields.
const (
	Default_TileProto_Layer_Version = uint32(1)
	Default_TileProto_Layer_Extent  = uint32(4096)
)

func (x *TileProto_Layer) Reset() {
	*x = TileProto_Layer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileProto_Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileProto_Layer) ProtoMessage() {}

func (x *TileProto_Layer) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileProto_Layer.ProtoReflect.Descriptor instead.
func (*TileProto_Layer) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0, 2}
}

var extRange_TileProto_Layer = []protoiface.ExtensionRangeV1{
	{Start: 16, End: 536870911},
}

// Deprecated: Use TileProto_Layer.ProtoReflect.Descriptor.ExtensionRanges instead.
func (*TileProto_Layer) ExtensionRangeArray() []protoiface.ExtensionRangeV1 {
	return extRange_TileProto_Layer
}

func (x *TileProto_Layer) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Default_TileProto_Layer_Version
}

func (x *TileProto_Layer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TileProto_Layer) GetFeatures() []*TileProto_Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *TileProto_Layer) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TileProto_Layer) GetValues() []*TileProto_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *TileProto_Layer) GetExtent() uint32 {
	if x != nil && x.Extent != nil {
		return *x.Extent
	}
	return Default_TileProto_Layer_Extent
}

var File_tiles_proto protoreflect.FileDescriptor

var file_tiles_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0xe4, 0x05, 0x0a, 0x09, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x2e, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x1a, 0xf2, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x09, 0x73, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x08, 0x08,
	0x08, 0x10, 0x80, 0x80, 0x80, 0x80, 0x02, 0x1a, 0x8c, 0x01, 0x0a, 0x07, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x11, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x3a,
	0x01, 0x30, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x36,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x08, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x1a, 0xda, 0x01, 0x0a, 0x05, 0x4c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x02, 0x28,
	0x0d, 0x3a, 0x01, 0x31, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x34, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x06, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x04, 0x34, 0x30, 0x39,
	0x36, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x74, 0x2a, 0x08, 0x08, 0x10, 0x10, 0x80, 0x80,
	0x80, 0x80, 0x02, 0x22, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x49, 0x4e, 0x45, 0x53,
	0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x4c, 0x59, 0x47,
	0x4f, 0x4e, 0x10, 0x03, 0x2a, 0x05, 0x08, 0x10, 0x10, 0x80, 0x40, 0x42, 0x1b, 0x48, 0x03, 0x5a,
	0x17, 0x64, 0x69, 0x61, 0x67, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f,
	0x62, 0x36, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_tiles_proto_rawDescOnce sync.Once
	file_tiles_proto_rawDescData = file_tiles_proto_rawDesc
)

func file_tiles_proto_rawDescGZIP() []byte {
	file_tiles_proto_rawDescOnce.Do(func() {
		file_tiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_tiles_proto_rawDescData)
	})
	return file_tiles_proto_rawDescData
}

var file_tiles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tiles_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tiles_proto_goTypes = []interface{}{
	(TileProto_GeomType)(0),   // 0: tiles.TileProto.GeomType
	(*TileProto)(nil),         // 1: tiles.TileProto
	(*TileProto_Value)(nil),   // 2: tiles.TileProto.Value
	(*TileProto_Feature)(nil), // 3: tiles.TileProto.Feature
	(*TileProto_Layer)(nil),   // 4: tiles.TileProto.Layer
}
var file_tiles_proto_depIdxs = []int32{
	4, // 0: tiles.TileProto.layers:type_name -> tiles.TileProto.Layer
	0, // 1: tiles.TileProto.Feature.type:type_name -> tiles.TileProto.GeomType
	3, // 2: tiles.TileProto.Layer.features:type_name -> tiles.TileProto.Feature
	2, // 3: tiles.TileProto.Layer.values:type_name -> tiles.TileProto.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tiles_proto_init() }
func file_tiles_proto_init() {
	if File_tiles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			case 3:
				return &v.extensionFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileProto_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			case 3:
				return &v.extensionFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileProto_Feature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileProto_Layer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			case 3:
				return &v.extensionFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tiles_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiles_proto_goTypes,
		DependencyIndexes: file_tiles_proto_depIdxs,
		EnumInfos:         file_tiles_proto_enumTypes,
		MessageInfos:      file_tiles_proto_msgTypes,
	}.Build()
	File_tiles_proto = out.File
	file_tiles_proto_rawDesc = nil
	file_tiles_proto_goTypes = nil
	file_tiles_proto_depIdxs = nil
}
