// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.25.3
// source: ui.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapLayerPosition int32

const (
	MapLayerPosition_MapLayerPositionEnd       MapLayerPosition = 0
	MapLayerPosition_MapLayerPositionRoads     MapLayerPosition = 1
	MapLayerPosition_MapLayerPositionBuildings MapLayerPosition = 2
)

// Enum value maps for MapLayerPosition.
var (
	MapLayerPosition_name = map[int32]string{
		0: "MapLayerPositionEnd",
		1: "MapLayerPositionRoads",
		2: "MapLayerPositionBuildings",
	}
	MapLayerPosition_value = map[string]int32{
		"MapLayerPositionEnd":       0,
		"MapLayerPositionRoads":     1,
		"MapLayerPositionBuildings": 2,
	}
)

func (x MapLayerPosition) Enum() *MapLayerPosition {
	p := new(MapLayerPosition)
	*p = x
	return p
}

func (x MapLayerPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapLayerPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_proto_enumTypes[0].Descriptor()
}

func (MapLayerPosition) Type() protoreflect.EnumType {
	return &file_ui_proto_enumTypes[0]
}

func (x MapLayerPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapLayerPosition.Descriptor instead.
func (MapLayerPosition) EnumDescriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{0}
}

type UIRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node         *NodeProto      `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Expression   string          `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Context      *FeatureIDProto `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Locked       bool            `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
	LogEvent     string          `protobuf:"bytes,5,opt,name=logEvent,proto3" json:"logEvent,omitempty"`
	LogMapCenter *PointProto     `protobuf:"bytes,6,opt,name=logMapCenter,proto3" json:"logMapCenter,omitempty"`
	LogMapZoom   float32         `protobuf:"fixed32,7,opt,name=logMapZoom,proto3" json:"logMapZoom,omitempty"`
	Session      uint64          `protobuf:"varint,8,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *UIRequestProto) Reset() {
	*x = UIRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIRequestProto) ProtoMessage() {}

func (x *UIRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIRequestProto.ProtoReflect.Descriptor instead.
func (*UIRequestProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{0}
}

func (x *UIRequestProto) GetNode() *NodeProto {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *UIRequestProto) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *UIRequestProto) GetContext() *FeatureIDProto {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UIRequestProto) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *UIRequestProto) GetLogEvent() string {
	if x != nil {
		return x.LogEvent
	}
	return ""
}

func (x *UIRequestProto) GetLogMapCenter() *PointProto {
	if x != nil {
		return x.LogMapCenter
	}
	return nil
}

func (x *UIRequestProto) GetLogMapZoom() float32 {
	if x != nil {
		return x.LogMapZoom
	}
	return 0
}

func (x *UIRequestProto) GetSession() uint64 {
	if x != nil {
		return x.Session
	}
	return 0
}

type UIResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stack        *StackProto      `protobuf:"bytes,1,opt,name=stack,proto3" json:"stack,omitempty"`
	Node         *NodeProto       `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Expression   string           `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	Highlighted  *FeatureIDsProto `protobuf:"bytes,4,opt,name=highlighted,proto3" json:"highlighted,omitempty"`
	GeoJSON      []*GeoJSONProto  `protobuf:"bytes,5,rep,name=geoJSON,proto3" json:"geoJSON,omitempty"` // References geojson array in response
	Layers       []*MapLayerProto `protobuf:"bytes,7,rep,name=layers,proto3" json:"layers,omitempty"`
	MapCenter    *PointProto      `protobuf:"bytes,8,opt,name=mapCenter,proto3" json:"mapCenter,omitempty"`
	Locked       bool             `protobuf:"varint,9,opt,name=locked,proto3" json:"locked,omitempty"`
	ChipValues   []int32          `protobuf:"varint,10,rep,packed,name=chipValues,proto3" json:"chipValues,omitempty"`
	LogDetail    string           `protobuf:"bytes,11,opt,name=logDetail,proto3" json:"logDetail,omitempty"`
	TilesChanged bool             `protobuf:"varint,12,opt,name=tilesChanged,proto3" json:"tilesChanged,omitempty"`
}

func (x *UIResponseProto) Reset() {
	*x = UIResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIResponseProto) ProtoMessage() {}

func (x *UIResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIResponseProto.ProtoReflect.Descriptor instead.
func (*UIResponseProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{1}
}

func (x *UIResponseProto) GetStack() *StackProto {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *UIResponseProto) GetNode() *NodeProto {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *UIResponseProto) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *UIResponseProto) GetHighlighted() *FeatureIDsProto {
	if x != nil {
		return x.Highlighted
	}
	return nil
}

func (x *UIResponseProto) GetGeoJSON() []*GeoJSONProto {
	if x != nil {
		return x.GeoJSON
	}
	return nil
}

func (x *UIResponseProto) GetLayers() []*MapLayerProto {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *UIResponseProto) GetMapCenter() *PointProto {
	if x != nil {
		return x.MapCenter
	}
	return nil
}

func (x *UIResponseProto) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *UIResponseProto) GetChipValues() []int32 {
	if x != nil {
		return x.ChipValues
	}
	return nil
}

func (x *UIResponseProto) GetLogDetail() string {
	if x != nil {
		return x.LogDetail
	}
	return ""
}

func (x *UIResponseProto) GetTilesChanged() bool {
	if x != nil {
		return x.TilesChanged
	}
	return false
}

type MapLayerProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Q      string           `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	V      string           `protobuf:"bytes,3,opt,name=v,proto3" json:"v,omitempty"`
	Before MapLayerPosition `protobuf:"varint,4,opt,name=before,proto3,enum=ui.MapLayerPosition" json:"before,omitempty"`
}

func (x *MapLayerProto) Reset() {
	*x = MapLayerProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapLayerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapLayerProto) ProtoMessage() {}

func (x *MapLayerProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapLayerProto.ProtoReflect.Descriptor instead.
func (*MapLayerProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{2}
}

func (x *MapLayerProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MapLayerProto) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *MapLayerProto) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *MapLayerProto) GetBefore() MapLayerPosition {
	if x != nil {
		return x.Before
	}
	return MapLayerPosition_MapLayerPositionEnd
}

type StackProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Substacks []*SubstackProto `protobuf:"bytes,1,rep,name=substacks,proto3" json:"substacks,omitempty"`
}

func (x *StackProto) Reset() {
	*x = StackProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackProto) ProtoMessage() {}

func (x *StackProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackProto.ProtoReflect.Descriptor instead.
func (*StackProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{3}
}

func (x *StackProto) GetSubstacks() []*SubstackProto {
	if x != nil {
		return x.Substacks
	}
	return nil
}

type SubstackProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines       []*LineProto `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Collapsable bool         `protobuf:"varint,2,opt,name=collapsable,proto3" json:"collapsable,omitempty"`
}

func (x *SubstackProto) Reset() {
	*x = SubstackProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubstackProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstackProto) ProtoMessage() {}

func (x *SubstackProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstackProto.ProtoReflect.Descriptor instead.
func (*SubstackProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{4}
}

func (x *SubstackProto) GetLines() []*LineProto {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *SubstackProto) GetCollapsable() bool {
	if x != nil {
		return x.Collapsable
	}
	return false
}

type LineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Line:
	//	*LineProto_Value
	//	*LineProto_LeftRightValue
	//	*LineProto_Expression
	//	*LineProto_Tags
	//	*LineProto_HistogramBar
	//	*LineProto_Swatch
	//	*LineProto_Shell
	//	*LineProto_Choice
	//	*LineProto_Header
	//	*LineProto_Error
	//	*LineProto_Action
	Line isLineProto_Line `protobuf_oneof:"line"`
}

func (x *LineProto) Reset() {
	*x = LineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineProto) ProtoMessage() {}

func (x *LineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineProto.ProtoReflect.Descriptor instead.
func (*LineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{5}
}

func (m *LineProto) GetLine() isLineProto_Line {
	if m != nil {
		return m.Line
	}
	return nil
}

func (x *LineProto) GetValue() *ValueLineProto {
	if x, ok := x.GetLine().(*LineProto_Value); ok {
		return x.Value
	}
	return nil
}

func (x *LineProto) GetLeftRightValue() *LeftRightValueLineProto {
	if x, ok := x.GetLine().(*LineProto_LeftRightValue); ok {
		return x.LeftRightValue
	}
	return nil
}

func (x *LineProto) GetExpression() *ExpressionLineProto {
	if x, ok := x.GetLine().(*LineProto_Expression); ok {
		return x.Expression
	}
	return nil
}

func (x *LineProto) GetTags() *TagsLineProto {
	if x, ok := x.GetLine().(*LineProto_Tags); ok {
		return x.Tags
	}
	return nil
}

func (x *LineProto) GetHistogramBar() *HistogramBarLineProto {
	if x, ok := x.GetLine().(*LineProto_HistogramBar); ok {
		return x.HistogramBar
	}
	return nil
}

func (x *LineProto) GetSwatch() *SwatchLineProto {
	if x, ok := x.GetLine().(*LineProto_Swatch); ok {
		return x.Swatch
	}
	return nil
}

func (x *LineProto) GetShell() *ShellLineProto {
	if x, ok := x.GetLine().(*LineProto_Shell); ok {
		return x.Shell
	}
	return nil
}

func (x *LineProto) GetChoice() *ChoiceLineProto {
	if x, ok := x.GetLine().(*LineProto_Choice); ok {
		return x.Choice
	}
	return nil
}

func (x *LineProto) GetHeader() *HeaderLineProto {
	if x, ok := x.GetLine().(*LineProto_Header); ok {
		return x.Header
	}
	return nil
}

func (x *LineProto) GetError() *ErrorLineProto {
	if x, ok := x.GetLine().(*LineProto_Error); ok {
		return x.Error
	}
	return nil
}

func (x *LineProto) GetAction() *ActionLineProto {
	if x, ok := x.GetLine().(*LineProto_Action); ok {
		return x.Action
	}
	return nil
}

type isLineProto_Line interface {
	isLineProto_Line()
}

type LineProto_Value struct {
	Value *ValueLineProto `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type LineProto_LeftRightValue struct {
	LeftRightValue *LeftRightValueLineProto `protobuf:"bytes,2,opt,name=leftRightValue,proto3,oneof"`
}

type LineProto_Expression struct {
	Expression *ExpressionLineProto `protobuf:"bytes,3,opt,name=expression,proto3,oneof"`
}

type LineProto_Tags struct {
	Tags *TagsLineProto `protobuf:"bytes,4,opt,name=tags,proto3,oneof"`
}

type LineProto_HistogramBar struct {
	HistogramBar *HistogramBarLineProto `protobuf:"bytes,5,opt,name=histogramBar,proto3,oneof"`
}

type LineProto_Swatch struct {
	Swatch *SwatchLineProto `protobuf:"bytes,6,opt,name=swatch,proto3,oneof"`
}

type LineProto_Shell struct {
	Shell *ShellLineProto `protobuf:"bytes,7,opt,name=shell,proto3,oneof"`
}

type LineProto_Choice struct {
	Choice *ChoiceLineProto `protobuf:"bytes,8,opt,name=choice,proto3,oneof"`
}

type LineProto_Header struct {
	Header *HeaderLineProto `protobuf:"bytes,9,opt,name=header,proto3,oneof"`
}

type LineProto_Error struct {
	Error *ErrorLineProto `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

type LineProto_Action struct {
	Action *ActionLineProto `protobuf:"bytes,11,opt,name=action,proto3,oneof"`
}

func (*LineProto_Value) isLineProto_Line() {}

func (*LineProto_LeftRightValue) isLineProto_Line() {}

func (*LineProto_Expression) isLineProto_Line() {}

func (*LineProto_Tags) isLineProto_Line() {}

func (*LineProto_HistogramBar) isLineProto_Line() {}

func (*LineProto_Swatch) isLineProto_Line() {}

func (*LineProto_Shell) isLineProto_Line() {}

func (*LineProto_Choice) isLineProto_Line() {}

func (*LineProto_Header) isLineProto_Line() {}

func (*LineProto_Error) isLineProto_Line() {}

func (*LineProto_Action) isLineProto_Line() {}

type ValueLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atom            *AtomProto `protobuf:"bytes,1,opt,name=atom,proto3" json:"atom,omitempty"`
	ClickExpression *NodeProto `protobuf:"bytes,2,opt,name=clickExpression,proto3" json:"clickExpression,omitempty"`
}

func (x *ValueLineProto) Reset() {
	*x = ValueLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueLineProto) ProtoMessage() {}

func (x *ValueLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueLineProto.ProtoReflect.Descriptor instead.
func (*ValueLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{6}
}

func (x *ValueLineProto) GetAtom() *AtomProto {
	if x != nil {
		return x.Atom
	}
	return nil
}

func (x *ValueLineProto) GetClickExpression() *NodeProto {
	if x != nil {
		return x.ClickExpression
	}
	return nil
}

type LeftRightValueLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  []*ClickableAtomProto `protobuf:"bytes,1,rep,name=left,proto3" json:"left,omitempty"`
	Right *ClickableAtomProto   `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *LeftRightValueLineProto) Reset() {
	*x = LeftRightValueLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeftRightValueLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftRightValueLineProto) ProtoMessage() {}

func (x *LeftRightValueLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftRightValueLineProto.ProtoReflect.Descriptor instead.
func (*LeftRightValueLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{7}
}

func (x *LeftRightValueLineProto) GetLeft() []*ClickableAtomProto {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *LeftRightValueLineProto) GetRight() *ClickableAtomProto {
	if x != nil {
		return x.Right
	}
	return nil
}

type ClickableAtomProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atom            *AtomProto `protobuf:"bytes,1,opt,name=atom,proto3" json:"atom,omitempty"`
	ClickExpression *NodeProto `protobuf:"bytes,2,opt,name=clickExpression,proto3" json:"clickExpression,omitempty"`
}

func (x *ClickableAtomProto) Reset() {
	*x = ClickableAtomProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickableAtomProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickableAtomProto) ProtoMessage() {}

func (x *ClickableAtomProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickableAtomProto.ProtoReflect.Descriptor instead.
func (*ClickableAtomProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{8}
}

func (x *ClickableAtomProto) GetAtom() *AtomProto {
	if x != nil {
		return x.Atom
	}
	return nil
}

func (x *ClickableAtomProto) GetClickExpression() *NodeProto {
	if x != nil {
		return x.ClickExpression
	}
	return nil
}

type ExpressionLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
}

func (x *ExpressionLineProto) Reset() {
	*x = ExpressionLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressionLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionLineProto) ProtoMessage() {}

func (x *ExpressionLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionLineProto.ProtoReflect.Descriptor instead.
func (*ExpressionLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{9}
}

func (x *ExpressionLineProto) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type TagsLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []*TagAtomProto `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *TagsLineProto) Reset() {
	*x = TagsLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsLineProto) ProtoMessage() {}

func (x *TagsLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsLineProto.ProtoReflect.Descriptor instead.
func (*TagsLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{10}
}

func (x *TagsLineProto) GetTags() []*TagAtomProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagAtomProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix          string     `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Key             string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           string     `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ClickExpression *NodeProto `protobuf:"bytes,4,opt,name=clickExpression,proto3" json:"clickExpression,omitempty"`
}

func (x *TagAtomProto) Reset() {
	*x = TagAtomProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagAtomProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAtomProto) ProtoMessage() {}

func (x *TagAtomProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAtomProto.ProtoReflect.Descriptor instead.
func (*TagAtomProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{11}
}

func (x *TagAtomProto) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *TagAtomProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TagAtomProto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TagAtomProto) GetClickExpression() *NodeProto {
	if x != nil {
		return x.ClickExpression
	}
	return nil
}

type HistogramBarLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range *AtomProto `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Value int32      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Total int32      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Index int32      `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *HistogramBarLineProto) Reset() {
	*x = HistogramBarLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistogramBarLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBarLineProto) ProtoMessage() {}

func (x *HistogramBarLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBarLineProto.ProtoReflect.Descriptor instead.
func (*HistogramBarLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{12}
}

func (x *HistogramBarLineProto) GetRange() *AtomProto {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *HistogramBarLineProto) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *HistogramBarLineProto) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *HistogramBarLineProto) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type SwatchLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label *AtomProto `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Index int32      `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *SwatchLineProto) Reset() {
	*x = SwatchLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwatchLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwatchLineProto) ProtoMessage() {}

func (x *SwatchLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwatchLineProto.ProtoReflect.Descriptor instead.
func (*SwatchLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{13}
}

func (x *SwatchLineProto) GetLabel() *AtomProto {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *SwatchLineProto) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ShellLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Functions []string `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *ShellLineProto) Reset() {
	*x = ShellLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellLineProto) ProtoMessage() {}

func (x *ShellLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellLineProto.ProtoReflect.Descriptor instead.
func (*ShellLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{14}
}

func (x *ShellLineProto) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

type ChoiceLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label *AtomProto   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Chips []*AtomProto `protobuf:"bytes,2,rep,name=chips,proto3" json:"chips,omitempty"`
}

func (x *ChoiceLineProto) Reset() {
	*x = ChoiceLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoiceLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceLineProto) ProtoMessage() {}

func (x *ChoiceLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceLineProto.ProtoReflect.Descriptor instead.
func (*ChoiceLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{15}
}

func (x *ChoiceLineProto) GetLabel() *AtomProto {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *ChoiceLineProto) GetChips() []*AtomProto {
	if x != nil {
		return x.Chips
	}
	return nil
}

type ChoiceProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChipValues []int32    `protobuf:"varint,1,rep,packed,name=chipValues,proto3" json:"chipValues,omitempty"`
	Label      *AtomProto `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *ChoiceProto) Reset() {
	*x = ChoiceProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoiceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceProto) ProtoMessage() {}

func (x *ChoiceProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceProto.ProtoReflect.Descriptor instead.
func (*ChoiceProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{16}
}

func (x *ChoiceProto) GetChipValues() []int32 {
	if x != nil {
		return x.ChipValues
	}
	return nil
}

func (x *ChoiceProto) GetLabel() *AtomProto {
	if x != nil {
		return x.Label
	}
	return nil
}

type HeaderLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title *AtomProto `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Close bool       `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	Share bool       `protobuf:"varint,3,opt,name=share,proto3" json:"share,omitempty"`
}

func (x *HeaderLineProto) Reset() {
	*x = HeaderLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderLineProto) ProtoMessage() {}

func (x *HeaderLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderLineProto.ProtoReflect.Descriptor instead.
func (*HeaderLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{17}
}

func (x *HeaderLineProto) GetTitle() *AtomProto {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *HeaderLineProto) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *HeaderLineProto) GetShare() bool {
	if x != nil {
		return x.Share
	}
	return false
}

type ErrorLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ErrorLineProto) Reset() {
	*x = ErrorLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorLineProto) ProtoMessage() {}

func (x *ErrorLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorLineProto.ProtoReflect.Descriptor instead.
func (*ErrorLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorLineProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ActionLineProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atom            *AtomProto `protobuf:"bytes,1,opt,name=atom,proto3" json:"atom,omitempty"`
	ClickExpression *NodeProto `protobuf:"bytes,2,opt,name=clickExpression,proto3" json:"clickExpression,omitempty"`
	InContext       bool       `protobuf:"varint,3,opt,name=inContext,proto3" json:"inContext,omitempty"`
}

func (x *ActionLineProto) Reset() {
	*x = ActionLineProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionLineProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionLineProto) ProtoMessage() {}

func (x *ActionLineProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionLineProto.ProtoReflect.Descriptor instead.
func (*ActionLineProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{19}
}

func (x *ActionLineProto) GetAtom() *AtomProto {
	if x != nil {
		return x.Atom
	}
	return nil
}

func (x *ActionLineProto) GetClickExpression() *NodeProto {
	if x != nil {
		return x.ClickExpression
	}
	return nil
}

func (x *ActionLineProto) GetInContext() bool {
	if x != nil {
		return x.InContext
	}
	return false
}

type AtomProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Atom:
	//	*AtomProto_Value
	//	*AtomProto_LabelledIcon
	//	*AtomProto_Download
	//	*AtomProto_Chip
	//	*AtomProto_Conditional
	Atom isAtomProto_Atom `protobuf_oneof:"atom"`
}

func (x *AtomProto) Reset() {
	*x = AtomProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomProto) ProtoMessage() {}

func (x *AtomProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomProto.ProtoReflect.Descriptor instead.
func (*AtomProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{20}
}

func (m *AtomProto) GetAtom() isAtomProto_Atom {
	if m != nil {
		return m.Atom
	}
	return nil
}

func (x *AtomProto) GetValue() string {
	if x, ok := x.GetAtom().(*AtomProto_Value); ok {
		return x.Value
	}
	return ""
}

func (x *AtomProto) GetLabelledIcon() *LabelledIconProto {
	if x, ok := x.GetAtom().(*AtomProto_LabelledIcon); ok {
		return x.LabelledIcon
	}
	return nil
}

func (x *AtomProto) GetDownload() string {
	if x, ok := x.GetAtom().(*AtomProto_Download); ok {
		return x.Download
	}
	return ""
}

func (x *AtomProto) GetChip() *ChipProto {
	if x, ok := x.GetAtom().(*AtomProto_Chip); ok {
		return x.Chip
	}
	return nil
}

func (x *AtomProto) GetConditional() *ConditionalProto {
	if x, ok := x.GetAtom().(*AtomProto_Conditional); ok {
		return x.Conditional
	}
	return nil
}

type isAtomProto_Atom interface {
	isAtomProto_Atom()
}

type AtomProto_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type AtomProto_LabelledIcon struct {
	LabelledIcon *LabelledIconProto `protobuf:"bytes,2,opt,name=labelledIcon,proto3,oneof"`
}

type AtomProto_Download struct {
	Download string `protobuf:"bytes,3,opt,name=download,proto3,oneof"`
}

type AtomProto_Chip struct {
	Chip *ChipProto `protobuf:"bytes,4,opt,name=chip,proto3,oneof"`
}

type AtomProto_Conditional struct {
	Conditional *ConditionalProto `protobuf:"bytes,5,opt,name=conditional,proto3,oneof"`
}

func (*AtomProto_Value) isAtomProto_Atom() {}

func (*AtomProto_LabelledIcon) isAtomProto_Atom() {}

func (*AtomProto_Download) isAtomProto_Atom() {}

func (*AtomProto_Chip) isAtomProto_Atom() {}

func (*AtomProto_Conditional) isAtomProto_Atom() {}

type LabelledIconProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icon  string `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *LabelledIconProto) Reset() {
	*x = LabelledIconProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabelledIconProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelledIconProto) ProtoMessage() {}

func (x *LabelledIconProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelledIconProto.ProtoReflect.Descriptor instead.
func (*LabelledIconProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{21}
}

func (x *LabelledIconProto) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *LabelledIconProto) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ChipProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Labels []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *ChipProto) Reset() {
	*x = ChipProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChipProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChipProto) ProtoMessage() {}

func (x *ChipProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChipProto.ProtoReflect.Descriptor instead.
func (*ChipProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{22}
}

func (x *ChipProto) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChipProto) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ConditionProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The value of the chips specified in indices need to match
	// the respective value for the element to be rendered.
	Indices []int32 `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Values  []int32 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *ConditionProto) Reset() {
	*x = ConditionProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionProto) ProtoMessage() {}

func (x *ConditionProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionProto.ProtoReflect.Descriptor instead.
func (*ConditionProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{23}
}

func (x *ConditionProto) GetIndices() []int32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *ConditionProto) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConditionalProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conditions []*ConditionProto `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Atoms      []*AtomProto      `protobuf:"bytes,2,rep,name=atoms,proto3" json:"atoms,omitempty"`
}

func (x *ConditionalProto) Reset() {
	*x = ConditionalProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalProto) ProtoMessage() {}

func (x *ConditionalProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalProto.ProtoReflect.Descriptor instead.
func (*ConditionalProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{24}
}

func (x *ConditionalProto) GetConditions() []*ConditionProto {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ConditionalProto) GetAtoms() []*AtomProto {
	if x != nil {
		return x.Atoms
	}
	return nil
}

type GeoJSONProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Condition *ConditionProto `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Index     int32           `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *GeoJSONProto) Reset() {
	*x = GeoJSONProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoJSONProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoJSONProto) ProtoMessage() {}

func (x *GeoJSONProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoJSONProto.ProtoReflect.Descriptor instead.
func (*GeoJSONProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{25}
}

func (x *GeoJSONProto) GetCondition() *ConditionProto {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *GeoJSONProto) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type FeatureIDsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespaces []string    `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Ids        []*IDsProto `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FeatureIDsProto) Reset() {
	*x = FeatureIDsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureIDsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureIDsProto) ProtoMessage() {}

func (x *FeatureIDsProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureIDsProto.ProtoReflect.Descriptor instead.
func (*FeatureIDsProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{26}
}

func (x *FeatureIDsProto) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *FeatureIDsProto) GetIds() []*IDsProto {
	if x != nil {
		return x.Ids
	}
	return nil
}

type IDsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *IDsProto) Reset() {
	*x = IDsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsProto) ProtoMessage() {}

func (x *IDsProto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsProto.ProtoReflect.Descriptor instead.
func (*IDsProto) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{27}
}

func (x *IDsProto) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_ui_proto protoreflect.FileDescriptor

var file_ui_proto_rawDesc = []byte{
	0x0a, 0x08, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x75, 0x69, 0x1a, 0x09,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x02, 0x0a, 0x0e, 0x55, 0x49,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49,
	0x44, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x4d, 0x61, 0x70, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x0c, 0x6c, 0x6f, 0x67, 0x4d, 0x61, 0x70, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x6f, 0x67, 0x4d, 0x61, 0x70, 0x5a, 0x6f, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x4d, 0x61, 0x70, 0x5a, 0x6f, 0x6f, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb7, 0x03, 0x0a, 0x0f, 0x55, 0x49, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x75, 0x69, 0x2e,
	0x53, 0x74, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x73, 0x74, 0x61, 0x63,
	0x6b, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0b, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x69, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x0b, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x07,
	0x67, 0x65, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x75, 0x69, 0x2e, 0x47, 0x65, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x07, 0x67, 0x65, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x12, 0x29, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x69, 0x2e, 0x4d, 0x61,
	0x70, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x32, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x6d, 0x61,
	0x70, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x68, 0x69, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a,
	0x0c, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x22, 0x6d, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x76, 0x12, 0x2c, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x75, 0x69, 0x2e, 0x4d, 0x61, 0x70, 0x4c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x22, 0x3d, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f,
	0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x22,
	0x56, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x23, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x70, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x6c,
	0x61, 0x70, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x22, 0xbf, 0x04, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x69, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c,
	0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x45, 0x0a, 0x0e, 0x6c, 0x65, 0x66, 0x74, 0x52, 0x69, 0x67, 0x68, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x69, 0x2e, 0x4c,
	0x65, 0x66, 0x74, 0x52, 0x69, 0x67, 0x68, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x6e,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x6c, 0x65, 0x66, 0x74, 0x52, 0x69,
	0x67, 0x68, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75,
	0x69, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6e, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x75, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x0c,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x69, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x42, 0x61, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52,
	0x0c, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x61, 0x72, 0x12, 0x2d, 0x0a,
	0x06, 0x73, 0x77, 0x61, 0x74, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x75, 0x69, 0x2e, 0x53, 0x77, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x73, 0x77, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2a, 0x0a, 0x05,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x69,
	0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48,
	0x00, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x69, 0x2e, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52,
	0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x69, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x69, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x06, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x6d, 0x0a, 0x0e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x04, 0x61,
	0x74, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41,
	0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x61, 0x74, 0x6f, 0x6d, 0x12, 0x38,
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x17, 0x4c, 0x65, 0x66, 0x74,
	0x52, 0x69, 0x67, 0x68, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x75, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12,
	0x2c, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x75, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x74, 0x6f,
	0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x22, 0x71, 0x0a,
	0x12, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x04, 0x61, 0x74, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x04, 0x61, 0x74, 0x6f, 0x6d, 0x12, 0x38, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x35, 0x0a, 0x13, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x0d, 0x54, 0x61, 0x67, 0x73, 0x4c,
	0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x41,
	0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x88,
	0x01, 0x0a, 0x0c, 0x54, 0x61, 0x67, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x38, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x7e, 0x0a, 0x15, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x61, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x23, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4c, 0x0a, 0x0f, 0x53, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69,
	0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2e, 0x0a, 0x0e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5b, 0x0a, 0x0f, 0x43, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41,
	0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x23, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x75, 0x69, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x63,
	0x68, 0x69, 0x70, 0x73, 0x22, 0x52, 0x0a, 0x0b, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x68, 0x69, 0x70, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x62, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e,
	0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x26, 0x0a, 0x0e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x8c, 0x01, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x04, 0x61, 0x74, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41, 0x74, 0x6f, 0x6d,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x61, 0x74, 0x6f, 0x6d, 0x12, 0x38, 0x0a, 0x0f, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x09, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x75, 0x69, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x49, 0x63, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x6c,
	0x65, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x68, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x43, 0x68, 0x69, 0x70, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x69, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x75, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x61, 0x74, 0x6f, 0x6d, 0x22, 0x3d, 0x0a, 0x11, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x39, 0x0a, 0x09, 0x43, 0x68,
	0x69, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x42, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x32, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x75, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x23, 0x0a, 0x05, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x05, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x22, 0x56, 0x0a, 0x0c, 0x47, 0x65, 0x6f, 0x4a, 0x53, 0x4f,
	0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x69, 0x2e, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x51,
	0x0a, 0x0f, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x75, 0x69, 0x2e, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x22, 0x1c, 0x0a, 0x08, 0x49, 0x44, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x2a,
	0x65, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x61, 0x70, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15,
	0x4d, 0x61, 0x70, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x6f, 0x61, 0x64, 0x73, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x61, 0x70, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x10, 0x02, 0x42, 0x19, 0x5a, 0x17, 0x64, 0x69, 0x61, 0x67, 0x6f, 0x6e,
	0x61, 0x6c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x36, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ui_proto_rawDescOnce sync.Once
	file_ui_proto_rawDescData = file_ui_proto_rawDesc
)

func file_ui_proto_rawDescGZIP() []byte {
	file_ui_proto_rawDescOnce.Do(func() {
		file_ui_proto_rawDescData = protoimpl.X.CompressGZIP(file_ui_proto_rawDescData)
	})
	return file_ui_proto_rawDescData
}

var file_ui_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_ui_proto_goTypes = []interface{}{
	(MapLayerPosition)(0),           // 0: ui.MapLayerPosition
	(*UIRequestProto)(nil),          // 1: ui.UIRequestProto
	(*UIResponseProto)(nil),         // 2: ui.UIResponseProto
	(*MapLayerProto)(nil),           // 3: ui.MapLayerProto
	(*StackProto)(nil),              // 4: ui.StackProto
	(*SubstackProto)(nil),           // 5: ui.SubstackProto
	(*LineProto)(nil),               // 6: ui.LineProto
	(*ValueLineProto)(nil),          // 7: ui.ValueLineProto
	(*LeftRightValueLineProto)(nil), // 8: ui.LeftRightValueLineProto
	(*ClickableAtomProto)(nil),      // 9: ui.ClickableAtomProto
	(*ExpressionLineProto)(nil),     // 10: ui.ExpressionLineProto
	(*TagsLineProto)(nil),           // 11: ui.TagsLineProto
	(*TagAtomProto)(nil),            // 12: ui.TagAtomProto
	(*HistogramBarLineProto)(nil),   // 13: ui.HistogramBarLineProto
	(*SwatchLineProto)(nil),         // 14: ui.SwatchLineProto
	(*ShellLineProto)(nil),          // 15: ui.ShellLineProto
	(*ChoiceLineProto)(nil),         // 16: ui.ChoiceLineProto
	(*ChoiceProto)(nil),             // 17: ui.ChoiceProto
	(*HeaderLineProto)(nil),         // 18: ui.HeaderLineProto
	(*ErrorLineProto)(nil),          // 19: ui.ErrorLineProto
	(*ActionLineProto)(nil),         // 20: ui.ActionLineProto
	(*AtomProto)(nil),               // 21: ui.AtomProto
	(*LabelledIconProto)(nil),       // 22: ui.LabelledIconProto
	(*ChipProto)(nil),               // 23: ui.ChipProto
	(*ConditionProto)(nil),          // 24: ui.ConditionProto
	(*ConditionalProto)(nil),        // 25: ui.ConditionalProto
	(*GeoJSONProto)(nil),            // 26: ui.GeoJSONProto
	(*FeatureIDsProto)(nil),         // 27: ui.FeatureIDsProto
	(*IDsProto)(nil),                // 28: ui.IDsProto
	(*NodeProto)(nil),               // 29: api.NodeProto
	(*FeatureIDProto)(nil),          // 30: api.FeatureIDProto
	(*PointProto)(nil),              // 31: geometry.PointProto
}
var file_ui_proto_depIdxs = []int32{
	29, // 0: ui.UIRequestProto.node:type_name -> api.NodeProto
	30, // 1: ui.UIRequestProto.context:type_name -> api.FeatureIDProto
	31, // 2: ui.UIRequestProto.logMapCenter:type_name -> geometry.PointProto
	4,  // 3: ui.UIResponseProto.stack:type_name -> ui.StackProto
	29, // 4: ui.UIResponseProto.node:type_name -> api.NodeProto
	27, // 5: ui.UIResponseProto.highlighted:type_name -> ui.FeatureIDsProto
	26, // 6: ui.UIResponseProto.geoJSON:type_name -> ui.GeoJSONProto
	3,  // 7: ui.UIResponseProto.layers:type_name -> ui.MapLayerProto
	31, // 8: ui.UIResponseProto.mapCenter:type_name -> geometry.PointProto
	0,  // 9: ui.MapLayerProto.before:type_name -> ui.MapLayerPosition
	5,  // 10: ui.StackProto.substacks:type_name -> ui.SubstackProto
	6,  // 11: ui.SubstackProto.lines:type_name -> ui.LineProto
	7,  // 12: ui.LineProto.value:type_name -> ui.ValueLineProto
	8,  // 13: ui.LineProto.leftRightValue:type_name -> ui.LeftRightValueLineProto
	10, // 14: ui.LineProto.expression:type_name -> ui.ExpressionLineProto
	11, // 15: ui.LineProto.tags:type_name -> ui.TagsLineProto
	13, // 16: ui.LineProto.histogramBar:type_name -> ui.HistogramBarLineProto
	14, // 17: ui.LineProto.swatch:type_name -> ui.SwatchLineProto
	15, // 18: ui.LineProto.shell:type_name -> ui.ShellLineProto
	16, // 19: ui.LineProto.choice:type_name -> ui.ChoiceLineProto
	18, // 20: ui.LineProto.header:type_name -> ui.HeaderLineProto
	19, // 21: ui.LineProto.error:type_name -> ui.ErrorLineProto
	20, // 22: ui.LineProto.action:type_name -> ui.ActionLineProto
	21, // 23: ui.ValueLineProto.atom:type_name -> ui.AtomProto
	29, // 24: ui.ValueLineProto.clickExpression:type_name -> api.NodeProto
	9,  // 25: ui.LeftRightValueLineProto.left:type_name -> ui.ClickableAtomProto
	9,  // 26: ui.LeftRightValueLineProto.right:type_name -> ui.ClickableAtomProto
	21, // 27: ui.ClickableAtomProto.atom:type_name -> ui.AtomProto
	29, // 28: ui.ClickableAtomProto.clickExpression:type_name -> api.NodeProto
	12, // 29: ui.TagsLineProto.tags:type_name -> ui.TagAtomProto
	29, // 30: ui.TagAtomProto.clickExpression:type_name -> api.NodeProto
	21, // 31: ui.HistogramBarLineProto.range:type_name -> ui.AtomProto
	21, // 32: ui.SwatchLineProto.label:type_name -> ui.AtomProto
	21, // 33: ui.ChoiceLineProto.label:type_name -> ui.AtomProto
	21, // 34: ui.ChoiceLineProto.chips:type_name -> ui.AtomProto
	21, // 35: ui.ChoiceProto.label:type_name -> ui.AtomProto
	21, // 36: ui.HeaderLineProto.title:type_name -> ui.AtomProto
	21, // 37: ui.ActionLineProto.atom:type_name -> ui.AtomProto
	29, // 38: ui.ActionLineProto.clickExpression:type_name -> api.NodeProto
	22, // 39: ui.AtomProto.labelledIcon:type_name -> ui.LabelledIconProto
	23, // 40: ui.AtomProto.chip:type_name -> ui.ChipProto
	25, // 41: ui.AtomProto.conditional:type_name -> ui.ConditionalProto
	24, // 42: ui.ConditionalProto.conditions:type_name -> ui.ConditionProto
	21, // 43: ui.ConditionalProto.atoms:type_name -> ui.AtomProto
	24, // 44: ui.GeoJSONProto.condition:type_name -> ui.ConditionProto
	28, // 45: ui.FeatureIDsProto.ids:type_name -> ui.IDsProto
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_ui_proto_init() }
func file_ui_proto_init() {
	if File_ui_proto != nil {
		return
	}
	file_api_proto_init()
	file_geometry_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ui_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapLayerProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubstackProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeftRightValueLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickableAtomProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressionLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagAtomProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistogramBarLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwatchLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoiceLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoiceProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionLineProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtomProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabelledIconProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChipProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionalProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoJSONProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureIDsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ui_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*LineProto_Value)(nil),
		(*LineProto_LeftRightValue)(nil),
		(*LineProto_Expression)(nil),
		(*LineProto_Tags)(nil),
		(*LineProto_HistogramBar)(nil),
		(*LineProto_Swatch)(nil),
		(*LineProto_Shell)(nil),
		(*LineProto_Choice)(nil),
		(*LineProto_Header)(nil),
		(*LineProto_Error)(nil),
		(*LineProto_Action)(nil),
	}
	file_ui_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*AtomProto_Value)(nil),
		(*AtomProto_LabelledIcon)(nil),
		(*AtomProto_Download)(nil),
		(*AtomProto_Chip)(nil),
		(*AtomProto_Conditional)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ui_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ui_proto_goTypes,
		DependencyIndexes: file_ui_proto_depIdxs,
		EnumInfos:         file_ui_proto_enumTypes,
		MessageInfos:      file_ui_proto_msgTypes,
	}.Build()
	File_ui_proto = out.File
	file_ui_proto_rawDesc = nil
	file_ui_proto_goTypes = nil
	file_ui_proto_depIdxs = nil
}
