name: Build release docker image

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-artifacts:
    name: "Build and publish b6 docker image"

    strategy:
      matrix:
        image-name: ["b6", "b6-minimal"]
        os: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Prepare nix"
      uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: Setup Cachix cache
      uses: cachix/cachix-action@v15
      with:
        name: diagonalworks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Build and publish docker image"
      env:
        IMAGE_NAME: ${{ matrix.os == 'ubuntu-latest' && matrix.image-name || format('{0}-{1}', matrix.image-name, matrix.os) }}
      run: |
        nix build .#${{ matrix.image-name }}-image
        ./result | docker load

        export TARBALL_TAG="$(nix eval --raw .#${{ matrix.image-name }}-image.imageName):$(nix eval --raw .#${{ matrix.image-name }}-image.imageTag)"
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

        docker tag "$TARBALL_TAG" ghcr.io/diagonalworks/diagonal-$IMAGE_NAME:latest
        docker push ghcr.io/diagonalworks/diagonal-$IMAGE_NAME:latest
