name: Build release docker image

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-artifacts:
    name: "Build and publish b6 docker image"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name: ["b6", "b6-minimal"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Prepare nix"
      uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: "Build and publish docker image"
      run: |
        nix build .#${{ matrix.image-name }} -image
        export TARBALL_TAG="$(nix eval --raw .#${{ matrix.image-name }}-image.imageName):$(nix eval --raw .#${{ matrix.image_name }}-image.imageTag)"
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        ./result | docker load
        docker tag "$TARBALL_TAG" ghcr.io/diagonalworks/diagonal-${{ matrix.image-name }}:latest
        docker push ghcr.io/diagonalworks/diagonal-${{ matrix.image-name }}:latest
