name: "CI"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: "Prepare nix"
      uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: "Get git tags for computing b6 version"
      run:
        git fetch --tags --force

    - name: "Build the Nix packages"
      run: |
        nix build .
        nix build .#python
        nix build .#b6-image

    - name: "Test the Makefile inside the combined devShell"
      run: |
        nix develop .#combined --command make all-tests
