name: aarch64 runner test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  release-artifacts:
    name: "Build and publish b6 docker image"

    strategy:
      matrix:
        image-name: ["b6", "b6-minimal"]
        os: [ "aarch64", "ubuntu-latest" ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Build and publish docker image"
      env:
        ARCH_LABEL: ${{ matrix.os == 'ubuntu-latest' && '""' || matrix.os }}
      run: |
        echo "arch_label=$ARCH_LABEL"
